import { onSchedule } from "firebase-functions/v2/scheduler";
import * as admin from "firebase-admin";

interface MissionEntry {
  completed?: boolean;
}

/**
 * Cloud Function: daily reminder for learners who haven't completed any of
 * today's missions yet (generated by generateDailyMissions). Writes a
 * 'reminder' notification doc, which sendPushOnNotificationCreate then
 * turns into an actual push -- this function only decides *who* to remind.
 */
export const sendQuestReminders = onSchedule(
  { schedule: "every day 17:00", timeZone: "Africa/Johannesburg" },
  async () => {
    const db = admin.firestore();
    const usersSnap = await db
      .collection("users")
      .where("role", "==", "learner")
      .get();

    const batch = db.batch();
    let remindersSent = 0;

    for (const userDoc of usersSnap.docs) {
      const uid = userDoc.id;
      const missionsDoc = await db
        .collection("daily_missions").doc(uid)
        .collection("today").doc("missions")
        .get();
      const missions: MissionEntry[] = missionsDoc.data()?.missions ?? [];
      if (missions.length === 0) continue;

      const completedCount = missions.filter((m) => m.completed).length;
      if (completedCount > 0) continue; // already played today

      const ref = db.collection("notifications").doc();
      batch.set(ref, {
        title: "Your quests are waiting! 🎯",
        body: "You haven't completed today's missions yet -- jump back in!",
        type: "reminder",
        recipientUid: uid,
        read: false,
        isRead: false,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      });
      remindersSent++;
    }

    if (remindersSent > 0) await batch.commit();
    console.log(`Sent ${remindersSent} quest reminders`);
  });
