'use strict';

/**
 * circuitBuilder packs: fill-in-the-blank "layout" puzzles, matching the
 * engine's real data contract (description, layout, blanks[], bank[],
 * labels{}) rather than an abstract node/edge graph — see
 * tools/gamegen/README.md. Each topic gets its own component vocabulary so
 * the same "complete the system" mechanic feels different per subject.
 */

function withLabels(components) {
  const labels = {};
  for (const c of components) labels[c.key] = `${c.emoji} ${c.name}`;
  return labels;
}

function puzzle(id, description, layout, blanks, bank, labels) {
  return { id, description, layout, blanks, bank, labels };
}

const TOPICS = {};

// ── Electric circuits (series) — the original hand-authored set ─────────
TOPICS.tech_g4_circuit = {
  circuits: [
    puzzle('series_one_bulb', 'Complete the series circuit: drag the missing component to the gap.', '🔋 —?— 💡', [{ position: 0, correctComponent: 'wire', emoji: '〰️', hint: 'Connects components' }], ['wire', 'bulb', 'switch', 'resistor'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('series_switch', 'Add a switch to control this circuit.', '🔋 — 💡 —?— 💡', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Opens and closes the circuit' }], ['wire', 'bulb', 'switch', 'resistor'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('series_battery', 'This circuit needs a power source!', '?— 🔘 — 💡', [{ position: 0, correctComponent: 'battery', emoji: '🔋', hint: 'Provides electrical energy' }], ['battery', 'bulb', 'switch', 'resistor'], { battery: '🔋 Battery', bulb: '💡 Bulb', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('series_two_gaps', 'Fill in BOTH missing components.', '🔋 —?— 💡 —?— 💡', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Controls the flow' }, { position: 1, correctComponent: 'wire', emoji: '〰️', hint: 'Connects the last bulb' }], ['wire', 'bulb', 'switch', 'resistor'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('resistor_protection', 'Protect the bulb by adding a resistor.', '🔋 — 💡 —?', [{ position: 0, correctComponent: 'resistor', emoji: '⬛', hint: 'Limits current flow' }], ['wire', 'bulb', 'switch', 'resistor'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('open_circuit', 'The bulb is off. What closes the circuit?', '🔋 — 💡 — ? — 🔋', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Must be closed for current to flow' }], ['wire', 'bulb', 'switch', 'battery'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch', battery: '🔋 Battery' }),
    puzzle('two_batteries', 'Add a second battery to increase the brightness.', '🔋 — ? — 💡 — 🔘', [{ position: 0, correctComponent: 'battery', emoji: '🔋', hint: 'More power = brighter bulb' }], ['battery', 'bulb', 'switch', 'wire'], { battery: '🔋 Battery', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('buzzer_circuit', 'Replace the bulb with a sound maker.', '🔋 — 🔘 — ?', [{ position: 0, correctComponent: 'buzzer', emoji: '🔔', hint: 'Makes a sound when current flows' }], ['buzzer', 'bulb', 'switch', 'wire'], { buzzer: '🔔 Buzzer', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('motor_circuit', 'Add a motor to make something spin.', '🔋 — 🔘 — ?', [{ position: 0, correctComponent: 'motor', emoji: '🌀', hint: 'Turns electrical energy into movement' }], ['motor', 'bulb', 'switch', 'wire'], { motor: '🌀 Motor', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('led_circuit', 'Replace the bulb with an energy-saving light.', '🔋 —?— 💡', [{ position: 0, correctComponent: 'LED', emoji: '🔆', hint: 'Uses much less energy than a bulb' }], ['LED', 'bulb', 'switch', 'wire'], { LED: '🔆 LED', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
  ],
};

TOPICS.tech_g7_circuit_series = {
  circuits: [
    ...TOPICS.tech_g4_circuit.circuits.map((c) => ({ ...c, id: `g7_${c.id}` })),
    puzzle('series_ammeter', 'An ammeter measures current and must be connected in series. What symbol represents it?', '🔋 —?— 💡', [{ position: 0, correctComponent: 'ammeter', emoji: '🅰️', hint: 'Measures current flowing through the circuit' }], ['ammeter', 'voltmeter', 'switch', 'resistor'], { ammeter: '🅰️ Ammeter', voltmeter: '🅥 Voltmeter', switch: '🔘 Switch', resistor: '⬛ Resistor' }),
    puzzle('series_variable_resistor', 'This component lets you change the resistance to dim a bulb.', '🔋 —?— 💡', [{ position: 0, correctComponent: 'rheostat', emoji: '🎚️', hint: 'A variable resistor' }], ['rheostat', 'resistor', 'switch', 'wire'], { rheostat: '🎚️ Rheostat', resistor: '⬛ Resistor', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('series_total_resistance', 'In a series circuit, adding a second resistor makes the total resistance...?', '⬛ —?— ⬛', [{ position: 0, correctComponent: 'increase', emoji: '⬆️', hint: 'Resistances in series add together' }], ['increase', 'decrease', 'stay the same', 'become zero'], { increase: '⬆️ Increase', decrease: '⬇️ Decrease', 'stay the same': '➡️ Stay the same', 'become zero': '0️⃣ Become zero' }),
    puzzle('series_one_break', 'If one bulb burns out in a series circuit, what happens to the rest?', '💡(out) — 💡 — 💡 —?', [{ position: 0, correctComponent: 'they all go off', emoji: '🌑', hint: 'A series circuit has only one path for current' }], ['they all go off', 'they stay on', 'they get brighter', 'nothing changes'], { 'they all go off': '🌑 They all go off', 'they stay on': '💡 They stay on', 'they get brighter': '✨ They get brighter', 'nothing changes': '➡️ Nothing changes' }),
    puzzle('series_current_same', 'In a series circuit, the current at every point is...?', '⚡ —?— ⚡', [{ position: 0, correctComponent: 'the same', emoji: '🟰', hint: 'Only one path means current cannot change along it' }], ['the same', 'different', 'zero', 'random'], { 'the same': '🟰 The same', different: '↕️ Different', zero: '0️⃣ Zero', random: '❓ Random' }),
  ],
};

TOPICS.tech_g7_circuit_parallel = {
  circuits: [
    puzzle('parallel_two_bulbs', 'In a parallel circuit each bulb has its own path. Complete it.', '🔋 ═╦═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'bulb', emoji: '💡', hint: 'Each branch needs its own bulb' }], ['bulb', 'switch', 'wire', 'resistor'], { bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire', resistor: '⬛ Resistor' }),
    puzzle('parallel_branch_switch', 'Add a switch that controls only ONE branch.', '🔋 ═╦═ 💡\n    ╚═?═ 💡', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Only affects its own branch' }], ['switch', 'wire', 'bulb', 'resistor'], { switch: '🔘 Switch', wire: '〰️ Wire', bulb: '💡 Bulb', resistor: '⬛ Resistor' }),
    puzzle('parallel_extra_branch', 'Add a third branch to the parallel circuit.', '🔋 ═╦═ 💡\n    ╠═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'bulb', emoji: '💡', hint: 'Parallel branches can be added independently' }], ['bulb', 'switch', 'wire'], { bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('parallel_junction', 'What connects the branches together?', '🔋 —?— ╦', [{ position: 0, correctComponent: 'wire', emoji: '〰️', hint: 'Wires join the branches at a junction' }], ['wire', 'bulb', 'switch'], { wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch' }),
    puzzle('parallel_main_switch', 'Add a switch that turns OFF the whole circuit.', '?— 🔋 ═╦═ 💡', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Placed before the split, it controls everything' }], ['switch', 'wire', 'bulb'], { switch: '🔘 Switch', wire: '〰️ Wire', bulb: '💡 Bulb' }),
    puzzle('parallel_resistor_branch', 'Protect one branch with a resistor.', '🔋 ═╦═ 💡\n    ╚═?═ 💡', [{ position: 0, correctComponent: 'resistor', emoji: '⬛', hint: 'Limits current in just that branch' }], ['resistor', 'wire', 'bulb', 'switch'], { resistor: '⬛ Resistor', wire: '〰️ Wire', bulb: '💡 Bulb', switch: '🔘 Switch' }),
    puzzle('parallel_battery_pair', 'Which component supplies power to all branches?', '?— ═╦═ 💡', [{ position: 0, correctComponent: 'battery', emoji: '🔋', hint: 'The power source is shared by all branches' }], ['battery', 'bulb', 'switch'], { battery: '🔋 Battery', bulb: '💡 Bulb', switch: '🔘 Switch' }),
    puzzle('parallel_led_branch', 'Add an LED to one branch to save energy.', '🔋 ═╦═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'LED', emoji: '🔆', hint: 'LEDs use less power than bulbs' }], ['LED', 'bulb', 'switch', 'wire'], { LED: '🔆 LED', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('parallel_motor_branch', 'Add a motor branch to spin a fan.', '🔋 ═╦═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'motor', emoji: '🌀', hint: 'Motors can run in their own branch' }], ['motor', 'bulb', 'switch', 'wire'], { motor: '🌀 Motor', bulb: '💡 Bulb', switch: '🔘 Switch', wire: '〰️ Wire' }),
    puzzle('parallel_buzzer_branch', 'Add a buzzer to a third branch.', '🔋 ═╦═ 💡\n    ╠═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'buzzer', emoji: '🔔', hint: 'A buzzer works fine on its own branch too' }], ['buzzer', 'bulb', 'switch'], { buzzer: '🔔 Buzzer', bulb: '💡 Bulb', switch: '🔘 Switch' }),
    puzzle('parallel_vs_series_gap', "Why doesn't one bulb going out affect the others in parallel?", '🔋 ═╦═ 💡(out)\n    ╚═?', [{ position: 0, correctComponent: 'bulb', emoji: '💡', hint: 'Each branch is an independent path' }], ['bulb', 'wire', 'switch'], { bulb: '💡 Bulb (still on)', wire: '〰️ Wire', switch: '🔘 Switch' }),
    puzzle('parallel_brightness', 'Add a bulb to a new branch without dimming the others.', '🔋 ═╦═ 💡\n    ╚═?', [{ position: 0, correctComponent: 'bulb', emoji: '💡', hint: 'Parallel branches keep the same voltage' }], ['bulb', 'resistor', 'switch'], { bulb: '💡 Bulb (full brightness)', resistor: '⬛ Resistor', switch: '🔘 Switch' }),
    puzzle('parallel_short_fix', 'A wire bridges two branches by mistake. What should replace it?', '🔋 ═╦═ 💡\n    ╚═?═ 💡', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'A switch lets you control that branch safely' }], ['switch', 'wire', 'bulb'], { switch: '🔘 Switch', wire: '〰️ Wire', bulb: '💡 Bulb' }),
    puzzle('parallel_household', 'Household wiring uses this circuit type so one appliance failing does not turn off the house. What connects each appliance?', '🔋 ═╦═ 📺\n    ╚═?', [{ position: 0, correctComponent: 'switch', emoji: '🔘', hint: 'Each appliance has its own switch/branch' }], ['switch', 'wire', 'bulb'], { switch: '🔘 Switch', wire: '〰️ Wire', bulb: '💡 Bulb' }),
    puzzle('parallel_total_current', 'What flows through the main wire before it splits into branches?', '?— ═╦═ 💡', [{ position: 0, correctComponent: 'battery', emoji: '🔋', hint: 'The battery supplies the total current for all branches' }], ['battery', 'bulb', 'resistor'], { battery: '🔋 Battery', bulb: '💡 Bulb', resistor: '⬛ Resistor' }),
  ],
};

function ecosystemLike(topicKey, verbLabel, nodeEmoji, links) {
  return {
    circuits: links.map((l, i) =>
      puzzle(
        `${topicKey}_${i}`,
        l.description,
        l.layout,
        [{ position: 0, correctComponent: l.correct, emoji: l.emoji, hint: l.hint }],
        l.bank,
        withLabels(l.bank.map((k) => ({ key: k, emoji: l.emojiFor ? l.emojiFor[k] : nodeEmoji, name: k })))
      )
    ),
  };
}

TOPICS.ns_g4_ecosystem = {
  circuits: [
    puzzle('sun_producer', 'Complete the energy flow: the sun powers this first link.', '☀️ —?— 🐇', [{ position: 0, correctComponent: 'grass', emoji: '🌱', hint: 'Plants capture the sun’s energy' }], ['grass', 'fox', 'hawk', 'water'], withLabels([{ key: 'grass', emoji: '🌱', name: 'Grass (producer)' }, { key: 'fox', emoji: '🦊', name: 'Fox' }, { key: 'hawk', emoji: '🦅', name: 'Hawk' }, { key: 'water', emoji: '💧', name: 'Water' }])),
    puzzle('herbivore_link', 'Which animal eats the grass?', '🌱 —?— 🦊', [{ position: 0, correctComponent: 'rabbit', emoji: '🐇', hint: 'A herbivore eats plants directly' }], ['rabbit', 'hawk', 'grass', 'sun'], withLabels([{ key: 'rabbit', emoji: '🐇', name: 'Rabbit (herbivore)' }, { key: 'hawk', emoji: '🦅', name: 'Hawk' }, { key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('predator_link', 'A fox eats the rabbit. What do we call the fox in this chain?', '🐇 —?— 🦅', [{ position: 0, correctComponent: 'fox', emoji: '🦊', hint: 'A predator that eats herbivores' }], ['fox', 'grass', 'sun', 'water'], withLabels([{ key: 'fox', emoji: '🦊', name: 'Fox (predator)' }, { key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'sun', emoji: '☀️', name: 'Sun' }, { key: 'water', emoji: '💧', name: 'Water' }])),
    puzzle('decomposer_link', 'What breaks down the dead fox and returns nutrients to the soil?', '🦊(dead) —?— 🌱', [{ position: 0, correctComponent: 'fungi', emoji: '🍄', hint: 'Decomposers recycle nutrients' }], ['fungi', 'hawk', 'rabbit', 'sun'], withLabels([{ key: 'fungi', emoji: '🍄', name: 'Fungi (decomposer)' }, { key: 'hawk', emoji: '🦅', name: 'Hawk' }, { key: 'rabbit', emoji: '🐇', name: 'Rabbit' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('apex_predator', 'What sits at the top of this food chain, with no natural predators here?', '🦊 —?', [{ position: 0, correctComponent: 'hawk', emoji: '🦅', hint: 'An apex predator' }], ['hawk', 'grass', 'fungi', 'sun'], withLabels([{ key: 'hawk', emoji: '🦅', name: 'Hawk (apex predator)' }, { key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'fungi', emoji: '🍄', name: 'Fungi' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('habitat_water', 'Every ecosystem link also needs this abiotic resource.', '🌱 ← ?', [{ position: 0, correctComponent: 'water', emoji: '💧', hint: 'A non-living but essential resource' }], ['water', 'fox', 'hawk', 'fungi'], withLabels([{ key: 'water', emoji: '💧', name: 'Water' }, { key: 'fox', emoji: '🦊', name: 'Fox' }, { key: 'hawk', emoji: '🦅', name: 'Hawk' }, { key: 'fungi', emoji: '🍄', name: 'Fungi' }])),
    puzzle('energy_source', 'What is the ultimate energy source for almost every ecosystem?', '?— 🌱', [{ position: 0, correctComponent: 'sun', emoji: '☀️', hint: 'Nearly all energy chains start here' }], ['sun', 'water', 'soil', 'fungi'], withLabels([{ key: 'sun', emoji: '☀️', name: 'Sun' }, { key: 'water', emoji: '💧', name: 'Water' }, { key: 'soil', emoji: '🟤', name: 'Soil' }, { key: 'fungi', emoji: '🍄', name: 'Fungi' }])),
    puzzle('soil_nutrients', 'Decomposed matter enriches this before plants can use it again.', '🍄 —?— 🌱', [{ position: 0, correctComponent: 'soil', emoji: '🟤', hint: 'Nutrients return to the soil' }], ['soil', 'hawk', 'fox', 'sun'], withLabels([{ key: 'soil', emoji: '🟤', name: 'Soil' }, { key: 'hawk', emoji: '🦅', name: 'Hawk' }, { key: 'fox', emoji: '🦊', name: 'Fox' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('scavenger_link', 'A vulture that eats the dead hawk is called a...?', '🦅(dead) —?', [{ position: 0, correctComponent: 'scavenger', emoji: '🦴', hint: 'Eats animals it did not kill' }], ['scavenger', 'producer', 'herbivore', 'sun'], withLabels([{ key: 'scavenger', emoji: '🦴', name: 'Scavenger (vulture)' }, { key: 'producer', emoji: '🌱', name: 'Producer' }, { key: 'herbivore', emoji: '🐇', name: 'Herbivore' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('balance_link', 'If foxes disappeared, what would likely increase first?', '🦊(gone) —?', [{ position: 0, correctComponent: 'rabbits', emoji: '🐇', hint: 'Fewer predators means more prey survive' }], ['rabbits', 'grass', 'sun', 'fungi'], withLabels([{ key: 'rabbits', emoji: '🐇', name: 'Rabbits' }, { key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'sun', emoji: '☀️', name: 'Sun' }, { key: 'fungi', emoji: '🍄', name: 'Fungi' }])),
    puzzle('overgrazing_link', 'Too many rabbits and not enough foxes can lead to overgrazed...?', '🐇🐇🐇 —?', [{ position: 0, correctComponent: 'grass', emoji: '🌱', hint: 'The producer level gets depleted' }], ['grass', 'water', 'soil', 'sun'], withLabels([{ key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'water', emoji: '💧', name: 'Water' }, { key: 'soil', emoji: '🟤', name: 'Soil' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
    puzzle('interdependence_link', 'This word describes how every part of the ecosystem relies on the others.', '🌱🐇🦊🦅 —?', [{ position: 0, correctComponent: 'interdependence', emoji: '🔗', hint: 'Nothing survives completely on its own' }], ['interdependence', 'isolation', 'competition', 'migration'], withLabels([{ key: 'interdependence', emoji: '🔗', name: 'Interdependence' }, { key: 'isolation', emoji: '🚧', name: 'Isolation' }, { key: 'competition', emoji: '⚔️', name: 'Competition' }, { key: 'migration', emoji: '🕊️', name: 'Migration' }])),
    puzzle('sa_example_kruger', 'In the Kruger National Park, this big cat is a top predator.', '🦌 —?', [{ position: 0, correctComponent: 'lion', emoji: '🦁', hint: 'An apex predator of the savanna' }], ['lion', 'impala', 'grass', 'termite'], withLabels([{ key: 'lion', emoji: '🦁', name: 'Lion' }, { key: 'impala', emoji: '🦌', name: 'Impala' }, { key: 'grass', emoji: '🌱', name: 'Grass' }, { key: 'termite', emoji: '🐜', name: 'Termite' }])),
    puzzle('sa_example_impala', 'This herbivore grazes on savanna grass in South Africa.', '🌱 —?', [{ position: 0, correctComponent: 'impala', emoji: '🦌', hint: 'A common antelope herbivore' }], ['impala', 'lion', 'termite', 'vulture'], withLabels([{ key: 'impala', emoji: '🦌', name: 'Impala' }, { key: 'lion', emoji: '🦁', name: 'Lion' }, { key: 'termite', emoji: '🐜', name: 'Termite' }, { key: 'vulture', emoji: '🦅', name: 'Vulture' }])),
    puzzle('sa_example_termite', 'This insect decomposes plant matter and aerates the soil.', '🌱(dead) —?', [{ position: 0, correctComponent: 'termite', emoji: '🐜', hint: 'A decomposer and soil engineer' }], ['termite', 'lion', 'impala', 'sun'], withLabels([{ key: 'termite', emoji: '🐜', name: 'Termite' }, { key: 'lion', emoji: '🦁', name: 'Lion' }, { key: 'impala', emoji: '🦌', name: 'Impala' }, { key: 'sun', emoji: '☀️', name: 'Sun' }])),
  ],
};

TOPICS.sci_g7_ecosystems = {
  circuits: TOPICS.ns_g4_ecosystem.circuits.slice(0, 10).map((c, i) => ({
    ...c,
    id: `food_web_${i}`,
    description: c.description.replace('ecosystem', 'food web'),
  })),
};

TOPICS.sci_g7_foodchains = {
  circuits: [
    puzzle('chain_1', 'Grassland food chain: what comes after the producer?', '🌱 —?— 🐇', [{ position: 0, correctComponent: 'primary consumer', emoji: '🐇', hint: 'Eats the producer directly' }], ['primary consumer', 'secondary consumer', 'decomposer', 'producer'], { 'primary consumer': '🐇 Primary consumer', 'secondary consumer': '🦊 Secondary consumer', decomposer: '🍄 Decomposer', producer: '🌱 Producer' }),
    puzzle('chain_2', 'What eats the primary consumer?', '🐇 —?— 🦅', [{ position: 0, correctComponent: 'secondary consumer', emoji: '🦊', hint: 'A predator of herbivores' }], ['secondary consumer', 'producer', 'decomposer', 'primary consumer'], { 'secondary consumer': '🦊 Secondary consumer', producer: '🌱 Producer', decomposer: '🍄 Decomposer', 'primary consumer': '🐇 Primary consumer' }),
    puzzle('chain_3', 'Which level starts almost every food chain?', '?— 🐇', [{ position: 0, correctComponent: 'producer', emoji: '🌱', hint: 'Makes its own food using sunlight' }], ['producer', 'decomposer', 'secondary consumer', 'tertiary consumer'], { producer: '🌱 Producer', decomposer: '🍄 Decomposer', 'secondary consumer': '🦊 Secondary consumer', 'tertiary consumer': '🦅 Tertiary consumer' }),
    puzzle('chain_4', 'The top predator with no natural enemies is the...?', '🦊 —?', [{ position: 0, correctComponent: 'tertiary consumer', emoji: '🦅', hint: 'Sits at the top of the chain' }], ['tertiary consumer', 'producer', 'primary consumer', 'decomposer'], { 'tertiary consumer': '🦅 Tertiary consumer', producer: '🌱 Producer', 'primary consumer': '🐇 Primary consumer', decomposer: '🍄 Decomposer' }),
    puzzle('chain_5', 'What recycles nutrients back to the producers?', '🦅(dead) —?— 🌱', [{ position: 0, correctComponent: 'decomposer', emoji: '🍄', hint: 'Breaks down dead organisms' }], ['decomposer', 'producer', 'primary consumer', 'secondary consumer'], { decomposer: '🍄 Decomposer', producer: '🌱 Producer', 'primary consumer': '🐇 Primary consumer', 'secondary consumer': '🦊 Secondary consumer' }),
    puzzle('chain_6', 'In the ocean, what is the producer usually called?', '?— 🐟', [{ position: 0, correctComponent: 'phytoplankton', emoji: '🦠', hint: 'Tiny plant-like organisms that photosynthesise' }], ['phytoplankton', 'zooplankton', 'shark', 'coral'], { phytoplankton: '🦠 Phytoplankton', zooplankton: '🦐 Zooplankton', shark: '🦈 Shark', coral: '🪸 Coral' }),
    puzzle('chain_7', 'What eats phytoplankton in the ocean food chain?', '🦠 —?', [{ position: 0, correctComponent: 'zooplankton', emoji: '🦐', hint: 'Tiny animals that graze on phytoplankton' }], ['zooplankton', 'shark', 'coral', 'phytoplankton'], { zooplankton: '🦐 Zooplankton', shark: '🦈 Shark', coral: '🪸 Coral', phytoplankton: '🦠 Phytoplankton' }),
    puzzle('chain_8', 'The apex predator of many ocean food chains is the...?', '🐟🐟 —?', [{ position: 0, correctComponent: 'shark', emoji: '🦈', hint: 'A top ocean predator' }], ['shark', 'coral', 'phytoplankton', 'zooplankton'], { shark: '🦈 Shark', coral: '🪸 Coral', phytoplankton: '🦠 Phytoplankton', zooplankton: '🦐 Zooplankton' }),
    puzzle('chain_9', 'Removing a middle link breaks the whole...?', '🌱-🐇-🦊-🦅 —?', [{ position: 0, correctComponent: 'food chain', emoji: '🔗', hint: 'Each link depends on the one before it' }], ['food chain', 'ecosystem service', 'habitat', 'biome'], { 'food chain': '🔗 Food chain', 'ecosystem service': '🛠️ Ecosystem service', habitat: '🏠 Habitat', biome: '🌍 Biome' }),
    puzzle('chain_10', 'Many food chains linked together form a...?', '🔗🔗🔗 —?', [{ position: 0, correctComponent: 'food web', emoji: '🕸️', hint: 'A network of interconnected food chains' }], ['food web', 'food chain', 'habitat', 'population'], { 'food web': '🕸️ Food web', 'food chain': '🔗 Food chain', habitat: '🏠 Habitat', population: '👥 Population' }),
  ],
};

TOPICS.sci_g7_atoms = {
  circuits: [
    puzzle('atom_center', 'What sits at the centre of an atom?', '⚛️ —?— e⁻', [{ position: 0, correctComponent: 'nucleus', emoji: '🔴', hint: 'Contains protons and neutrons' }], ['nucleus', 'electron', 'molecule', 'ion'], { nucleus: '🔴 Nucleus', electron: '⚡ Electron', molecule: '🔗 Molecule', ion: '➕ Ion' }),
    puzzle('positive_particle', 'Which particle in the nucleus has a positive charge?', '🔴 —?', [{ position: 0, correctComponent: 'proton', emoji: '➕', hint: 'Positively charged, found in the nucleus' }], ['proton', 'neutron', 'electron', 'nucleus'], { proton: '➕ Proton', neutron: '⚪ Neutron', electron: '⚡ Electron', nucleus: '🔴 Nucleus' }),
    puzzle('neutral_particle', 'Which particle in the nucleus has no charge?', '🔴 —?', [{ position: 0, correctComponent: 'neutron', emoji: '⚪', hint: 'Neutral charge, found in the nucleus' }], ['neutron', 'proton', 'electron', 'ion'], { neutron: '⚪ Neutron', proton: '➕ Proton', electron: '⚡ Electron', ion: '➕ Ion' }),
    puzzle('orbiting_particle', 'What orbits the nucleus with a negative charge?', '🔴 —?', [{ position: 0, correctComponent: 'electron', emoji: '⚡', hint: 'Negatively charged, moves around the nucleus' }], ['electron', 'proton', 'neutron', 'molecule'], { electron: '⚡ Electron', proton: '➕ Proton', neutron: '⚪ Neutron', molecule: '🔗 Molecule' }),
    puzzle('bonding_link', 'Two hydrogen atoms and one oxygen atom bond to form...?', '⚛️⚛️⚛️ —?', [{ position: 0, correctComponent: 'water molecule', emoji: '💧', hint: 'H₂O — atoms bonded together' }], ['water molecule', 'ion', 'nucleus', 'compound'], { 'water molecule': '💧 Water molecule (H₂O)', ion: '➕ Ion', nucleus: '🔴 Nucleus', compound: '🧪 Compound' }),
    puzzle('molecule_def', 'Two or more atoms bonded together form a...?', '⚛️—⚛️ —?', [{ position: 0, correctComponent: 'molecule', emoji: '🔗', hint: 'A group of bonded atoms' }], ['molecule', 'nucleus', 'proton', 'ion'], { molecule: '🔗 Molecule', nucleus: '🔴 Nucleus', proton: '➕ Proton', ion: '➕ Ion' }),
    puzzle('compound_def', 'A molecule made of two or more DIFFERENT elements is a...?', 'H—H—O —?', [{ position: 0, correctComponent: 'compound', emoji: '🧪', hint: 'Different elements chemically bonded' }], ['compound', 'element', 'mixture', 'atom'], { compound: '🧪 Compound', element: '🔵 Element', mixture: '🥣 Mixture', atom: '⚛️ Atom' }),
    puzzle('element_def', 'A substance made of only ONE type of atom is called an...?', '⚛️⚛️⚛️ —?', [{ position: 0, correctComponent: 'element', emoji: '🔵', hint: 'The purest form of a substance' }], ['element', 'compound', 'mixture', 'molecule'], { element: '🔵 Element', compound: '🧪 Compound', mixture: '🥣 Mixture', molecule: '🔗 Molecule' }),
    puzzle('ion_def', 'An atom that gains or loses an electron becomes a charged...?', '⚛️(±) —?', [{ position: 0, correctComponent: 'ion', emoji: '➕', hint: 'An atom with an electric charge' }], ['ion', 'nucleus', 'compound', 'molecule'], { ion: '➕ Ion', nucleus: '🔴 Nucleus', compound: '🧪 Compound', molecule: '🔗 Molecule' }),
    puzzle('periodic_table', 'Elements are organised by atomic number in the...?', '🔵🔵🔵 —?', [{ position: 0, correctComponent: 'periodic table', emoji: '📊', hint: 'A chart organising all known elements' }], ['periodic table', 'molecule chart', 'ion list', 'atom map'], { 'periodic table': '📊 Periodic table', 'molecule chart': '🔗 Molecule chart', 'ion list': '➕ Ion list', 'atom map': '⚛️ Atom map' }),
    puzzle('mixture_def', 'Sand and water stirred together (not chemically bonded) form a...?', '🏖️+💧 —?', [{ position: 0, correctComponent: 'mixture', emoji: '🥣', hint: 'Substances combined without a chemical bond' }], ['mixture', 'compound', 'element', 'ion'], { mixture: '🥣 Mixture', compound: '🧪 Compound', element: '🔵 Element', ion: '➕ Ion' }),
    puzzle('atomic_number', 'The number of protons in an atom is its...?', '➕➕➕ —?', [{ position: 0, correctComponent: 'atomic number', emoji: '🔢', hint: 'Identifies which element an atom is' }], ['atomic number', 'atomic mass', 'charge', 'valence'], { 'atomic number': '🔢 Atomic number', 'atomic mass': '⚖️ Atomic mass', charge: '➕ Charge', valence: '🔗 Valence' }),
    puzzle('salt_bond', 'Table salt (NaCl) is a compound formed by bonding sodium and...?', 'Na—? ', [{ position: 0, correctComponent: 'chlorine', emoji: '🧂', hint: 'Sodium bonds with this element to form salt' }], ['chlorine', 'oxygen', 'hydrogen', 'carbon'], { chlorine: '🧂 Chlorine', oxygen: '💨 Oxygen', hydrogen: '💧 Hydrogen', carbon: '⚫ Carbon' }),
    puzzle('co2_bond', 'Carbon bonded with two oxygen atoms forms...?', 'C—O—O —?', [{ position: 0, correctComponent: 'carbon dioxide', emoji: '💨', hint: 'CO₂ — a gas we exhale' }], ['carbon dioxide', 'water molecule', 'table salt', 'oxygen gas'], { 'carbon dioxide': '💨 Carbon dioxide (CO₂)', 'water molecule': '💧 Water molecule', 'table salt': '🧂 Table salt', 'oxygen gas': '💨 Oxygen gas' }),
    puzzle('states_link', 'Atoms in a solid are packed closely and vibrate in place, unlike in a...?', '⚛️⚛️⚛️(tight) —?', [{ position: 0, correctComponent: 'gas', emoji: '💨', hint: 'Atoms move freely and spread far apart' }], ['gas', 'solid', 'crystal', 'nucleus'], { gas: '💨 Gas', solid: '🧊 Solid', crystal: '💎 Crystal', nucleus: '🔴 Nucleus' }),
  ],
};

TOPICS.tech_g4_machines = {
  circuits: [
    puzzle('lever_setup', 'A lever needs a fixed point to pivot on. What is it called?', '🪜 —?— ⚖️', [{ position: 0, correctComponent: 'fulcrum', emoji: '🔺', hint: 'The lever pivots on this point' }], ['fulcrum', 'pulley', 'wedge', 'wheel'], { fulcrum: '🔺 Fulcrum', pulley: '🎡 Pulley', wedge: '🔻 Wedge', wheel: '⚙️ Wheel' }),
    puzzle('pulley_setup', 'What simple machine uses a wheel and rope to lift a load?', '🪢 —?— 📦', [{ position: 0, correctComponent: 'pulley', emoji: '🎡', hint: 'Changes the direction of a pulling force' }], ['pulley', 'lever', 'wedge', 'screw'], { pulley: '🎡 Pulley', lever: '⚖️ Lever', wedge: '🔻 Wedge', screw: '🌀 Screw' }),
    puzzle('inclined_plane', 'A ramp used to lift a load with less force is called a(n)...?', '📦 —?— 🚚', [{ position: 0, correctComponent: 'inclined plane', emoji: '📐', hint: 'A sloped surface, like a ramp' }], ['inclined plane', 'wedge', 'wheel', 'lever'], { 'inclined plane': '📐 Inclined plane', wedge: '🔻 Wedge', wheel: '⚙️ Wheel', lever: '⚖️ Lever' }),
    puzzle('wedge_tool', 'An axe blade is an example of which simple machine?', '🪓 —?', [{ position: 0, correctComponent: 'wedge', emoji: '🔻', hint: 'Splits or cuts things apart' }], ['wedge', 'screw', 'pulley', 'lever'], { wedge: '🔻 Wedge', screw: '🌀 Screw', pulley: '🎡 Pulley', lever: '⚖️ Lever' }),
    puzzle('screw_tool', 'A spiral inclined plane wrapped around a cylinder is called a...?', '🔩 —?', [{ position: 0, correctComponent: 'screw', emoji: '🌀', hint: 'Converts turning force into linear force' }], ['screw', 'wedge', 'lever', 'wheel'], { screw: '🌀 Screw', wedge: '🔻 Wedge', lever: '⚖️ Lever', wheel: '⚙️ Wheel' }),
    puzzle('wheel_axle', 'A doorknob turning a rod is an example of a...?', '🚪 —?', [{ position: 0, correctComponent: 'wheel and axle', emoji: '⚙️', hint: 'A wheel fixed to a rod that turns together' }], ['wheel and axle', 'pulley', 'wedge', 'screw'], { 'wheel and axle': '⚙️ Wheel and axle', pulley: '🎡 Pulley', wedge: '🔻 Wedge', screw: '🌀 Screw' }),
    puzzle('seesaw_lever', 'A seesaw is a first-class example of a...?', '🧒⚖️🧒 —?', [{ position: 0, correctComponent: 'lever', emoji: '⚖️', hint: 'The fulcrum is in the middle' }], ['lever', 'pulley', 'screw', 'wedge'], { lever: '⚖️ Lever', pulley: '🎡 Pulley', screw: '🌀 Screw', wedge: '🔻 Wedge' }),
    puzzle('wheelbarrow_lever', 'A wheelbarrow is a second-class lever — where is the load?', '🛒 —?', [{ position: 0, correctComponent: 'between fulcrum and effort', emoji: '📦', hint: 'The load sits between the wheel (fulcrum) and your hands (effort)' }], ['between fulcrum and effort', 'at the fulcrum', 'past the effort', 'not on the lever'], { 'between fulcrum and effort': '📦 Between fulcrum and effort', 'at the fulcrum': '🔺 At the fulcrum', 'past the effort': '➡️ Past the effort', 'not on the lever': '🚫 Not on the lever' }),
    puzzle('flagpole_pulley', 'Raising a flag on a flagpole uses which simple machine?', '🚩 —?', [{ position: 0, correctComponent: 'pulley', emoji: '🎡', hint: 'A rope runs over a wheel at the top' }], ['pulley', 'lever', 'wedge', 'screw'], { pulley: '🎡 Pulley', lever: '⚖️ Lever', wedge: '🔻 Wedge', screw: '🌀 Screw' }),
    puzzle('jar_lid_screw', 'The threads on a jar lid are an example of a...?', '🫙 —?', [{ position: 0, correctComponent: 'screw', emoji: '🌀', hint: 'A spiral thread that grips as it turns' }], ['screw', 'wedge', 'lever', 'pulley'], { screw: '🌀 Screw', wedge: '🔻 Wedge', lever: '⚖️ Lever', pulley: '🎡 Pulley' }),
  ],
};

function circuitsFor(topicKey, entries) {
  TOPICS[topicKey] = {
    circuits: entries.map((e, i) => puzzle(`${topicKey}_${i}`, e.description, e.layout, e.blanks, e.bank, e.labels)),
  };
}

circuitsFor('tech_g7_mechanisms', [
  { description: 'A gear with more teeth turning a gear with fewer teeth makes it spin...?', layout: '⚙️(big) —?— ⚙️(small)', blanks: [{ position: 0, correctComponent: 'faster', emoji: '⚡', hint: 'Fewer teeth means faster rotation' }], bank: ['faster', 'slower', 'backward', 'not at all'], labels: { faster: '⚡ Faster', slower: '🐢 Slower', backward: '↩️ Backward', 'not at all': '🚫 Not at all' } },
  { description: 'Two meshed gears always spin in...?', layout: '⚙️ —?— ⚙️', blanks: [{ position: 0, correctComponent: 'opposite directions', emoji: '↔️', hint: 'One clockwise, one anticlockwise' }], bank: ['opposite directions', 'the same direction', 'random directions', 'they stop'], labels: { 'opposite directions': '↔️ Opposite directions', 'the same direction': '➡️ Same direction', 'random directions': '❓ Random', 'they stop': '🛑 They stop' } },
  { description: 'What simple machine uses a fixed point to lift a heavy load with less effort?', layout: '⚖️ —?', blanks: [{ position: 0, correctComponent: 'lever', emoji: '⚖️', hint: 'Pivots around a fulcrum' }], bank: ['lever', 'gear', 'pulley', 'cam'], labels: { lever: '⚖️ Lever', gear: '⚙️ Gear', pulley: '🎡 Pulley', cam: '🔄 Cam' } },
  { description: 'A system of pulleys that reduces the force needed to lift a load is called a...?', layout: '🎡🎡 —?', blanks: [{ position: 0, correctComponent: 'block and tackle', emoji: '🪢', hint: 'Multiple pulleys working together' }], bank: ['block and tackle', 'single pulley', 'gear train', 'lever'], labels: { 'block and tackle': '🪢 Block and tackle', 'single pulley': '🎡 Single pulley', 'gear train': '⚙️ Gear train', lever: '⚖️ Lever' } },
  { description: 'A chain of gears connected together is called a...?', layout: '⚙️⚙️⚙️ —?', blanks: [{ position: 0, correctComponent: 'gear train', emoji: '⚙️', hint: 'Multiple gears meshed in sequence' }], bank: ['gear train', 'pulley system', 'lever arm', 'cam shaft'], labels: { 'gear train': '⚙️ Gear train', 'pulley system': '🎡 Pulley system', 'lever arm': '⚖️ Lever arm', 'cam shaft': '🔄 Cam shaft' } },
  { description: 'A rotating oval-shaped part that converts rotary motion into up-down motion is a...?', layout: '🔄 —?', blanks: [{ position: 0, correctComponent: 'cam', emoji: '🔄', hint: 'Used in engines to open and close valves' }], bank: ['cam', 'gear', 'lever', 'pulley'], labels: { cam: '🔄 Cam', gear: '⚙️ Gear', lever: '⚖️ Lever', pulley: '🎡 Pulley' } },
  { description: 'A bicycle uses this mechanism to transfer pedal power to the back wheel.', layout: '🚲 —?', blanks: [{ position: 0, correctComponent: 'chain and gears', emoji: '⛓️', hint: 'Connects the pedals to the wheel' }], bank: ['chain and gears', 'pulley', 'lever', 'cam'], labels: { 'chain and gears': '⛓️ Chain and gears', pulley: '🎡 Pulley', lever: '⚖️ Lever', cam: '🔄 Cam' } },
  { description: 'A crane uses this mechanism to lift heavy loads high into the air.', layout: '🏗️ —?', blanks: [{ position: 0, correctComponent: 'pulley', emoji: '🎡', hint: 'A rope and wheel system for lifting' }], bank: ['pulley', 'cam', 'gear', 'wedge'], labels: { pulley: '🎡 Pulley', cam: '🔄 Cam', gear: '⚙️ Gear', wedge: '🔻 Wedge' } },
  { description: 'A small gear driving a large gear makes the large gear turn with more...?', layout: '⚙️(small) —?— ⚙️(big)', blanks: [{ position: 0, correctComponent: 'force (torque)', emoji: '💪', hint: 'Speed is traded for turning force' }], bank: ['force (torque)', 'speed', 'noise', 'colour'], labels: { 'force (torque)': '💪 Force (torque)', speed: '⚡ Speed', noise: '🔊 Noise', colour: '🎨 Colour' } },
  { description: 'What do we call machines that combine several simple machines together?', layout: '⚙️⚖️🎡 —?', blanks: [{ position: 0, correctComponent: 'compound machine', emoji: '🛠️', hint: 'Two or more simple machines working together' }], bank: ['compound machine', 'simple machine', 'engine only', 'lever only'], labels: { 'compound machine': '🛠️ Compound machine', 'simple machine': '⚙️ Simple machine', 'engine only': '🏎️ Engine only', 'lever only': '⚖️ Lever only' } },
]);

circuitsFor('tech_g7_structures', [
  { description: 'A triangle shape in a bridge truss resists deforming because it is naturally...?', layout: '🔺 —?', blanks: [{ position: 0, correctComponent: 'rigid', emoji: '🔒', hint: 'Triangles keep their shape under load' }], bank: ['rigid', 'flexible', 'weak', 'heavy'], labels: { rigid: '🔒 Rigid', flexible: '🤸 Flexible', weak: '🪶 Weak', heavy: '🏋️ Heavy' } },
  { description: 'A force that pushes or squeezes a structure is called...?', layout: '⬅️🏛️➡️ —?', blanks: [{ position: 0, correctComponent: 'compression', emoji: '🗜️', hint: 'A squeezing force' }], bank: ['compression', 'tension', 'shear', 'torsion'], labels: { compression: '🗜️ Compression', tension: '↔️ Tension', shear: '✂️ Shear', torsion: '🌀 Torsion' } },
  { description: 'A force that stretches or pulls a structure apart is called...?', layout: '⬅️➡️🔗 —?', blanks: [{ position: 0, correctComponent: 'tension', emoji: '↔️', hint: 'A pulling/stretching force' }], bank: ['tension', 'compression', 'shear', 'torsion'], labels: { tension: '↔️ Tension', compression: '🗜️ Compression', shear: '✂️ Shear', torsion: '🌀 Torsion' } },
  { description: 'What structural part transfers a building’s weight down to the ground?', layout: '🏢 —?', blanks: [{ position: 0, correctComponent: 'foundation', emoji: '🧱', hint: 'The base a structure rests on' }], bank: ['foundation', 'roof', 'beam', 'column'], labels: { foundation: '🧱 Foundation', roof: '🏠 Roof', beam: '➖ Beam', column: '🏛️ Column' } },
  { description: 'A horizontal support that carries weight across a gap is called a...?', layout: '🏛️ —?— 🏛️', blanks: [{ position: 0, correctComponent: 'beam', emoji: '➖', hint: 'Spans horizontally between supports' }], bank: ['beam', 'column', 'foundation', 'truss'], labels: { beam: '➖ Beam', column: '🏛️ Column', foundation: '🧱 Foundation', truss: '🔺 Truss' } },
  { description: 'A vertical support that carries load down to the foundation is a...?', layout: '🏠 —?— 🧱', blanks: [{ position: 0, correctComponent: 'column', emoji: '🏛️', hint: 'Stands upright, carries vertical load' }], bank: ['column', 'beam', 'truss', 'arch'], labels: { column: '🏛️ Column', beam: '➖ Beam', truss: '🔺 Truss', arch: '🌉 Arch' } },
  { description: 'A curved structure that spreads load outward and down, used in bridges, is an...?', layout: '🌉 —?', blanks: [{ position: 0, correctComponent: 'arch', emoji: '🌉', hint: 'A curved load-bearing structure' }], bank: ['arch', 'beam', 'truss', 'column'], labels: { arch: '🌉 Arch', beam: '➖ Beam', truss: '🔺 Truss', column: '🏛️ Column' } },
  { description: 'A framework of triangles used to support a roof or bridge is a...?', layout: '🔺🔺🔺 —?', blanks: [{ position: 0, correctComponent: 'truss', emoji: '🔺', hint: 'A rigid framework of triangles' }], bank: ['truss', 'beam', 'column', 'arch'], labels: { truss: '🔺 Truss', beam: '➖ Beam', column: '🏛️ Column', arch: '🌉 Arch' } },
  { description: 'A wide base helps a tall structure resist toppling by lowering its...?', layout: '🗼(wide base) —?', blanks: [{ position: 0, correctComponent: 'centre of gravity', emoji: '⚖️', hint: 'The point where weight is balanced' }], bank: ['centre of gravity', 'height', 'colour', 'weight'], labels: { 'centre of gravity': '⚖️ Centre of gravity', height: '📏 Height', colour: '🎨 Colour', weight: '🏋️ Weight' } },
  { description: 'Cross-bracing (diagonal supports) mainly resists which force acting sideways on a structure?', layout: '🏗️(cross-braced) —?', blanks: [{ position: 0, correctComponent: 'wind load', emoji: '💨', hint: 'Sideways force from wind or earthquakes' }], bank: ['wind load', 'gravity only', 'sunlight', 'rain'], labels: { 'wind load': '💨 Wind load', 'gravity only': '⬇️ Gravity only', sunlight: '☀️ Sunlight', rain: '🌧️ Rain' } },
]);

circuitsFor('tech_g7_electronics', [
  { description: 'A switch that opens or closes ONE circuit path is called a...?', layout: '🔘 —?', blanks: [{ position: 0, correctComponent: 'simple switch', emoji: '🔘', hint: 'One path, on or off' }], bank: ['simple switch', 'two-way switch', 'sensor', 'diode'], labels: { 'simple switch': '🔘 Simple switch', 'two-way switch': '🔀 Two-way switch', sensor: '📡 Sensor', diode: '➡️ Diode' } },
  { description: 'A switch that can control a light from TWO different locations is a...?', layout: '🔀 —?', blanks: [{ position: 0, correctComponent: 'two-way switch', emoji: '🔀', hint: 'Used at the top and bottom of a staircase' }], bank: ['two-way switch', 'simple switch', 'push button', 'relay'], labels: { 'two-way switch': '🔀 Two-way switch', 'simple switch': '🔘 Simple switch', 'push button': '🔲 Push button', relay: '🧲 Relay' } },
  { description: 'A component that only lets current flow in one direction is a...?', layout: '➡️ —?', blanks: [{ position: 0, correctComponent: 'diode', emoji: '➡️', hint: 'One-way valve for electricity' }], bank: ['diode', 'resistor', 'switch', 'capacitor'], labels: { diode: '➡️ Diode', resistor: '⬛ Resistor', switch: '🔘 Switch', capacitor: '🔋 Capacitor' } },
  { description: 'A component that detects light, heat or movement to trigger a circuit is a...?', layout: '📡 —?', blanks: [{ position: 0, correctComponent: 'sensor', emoji: '📡', hint: 'Detects changes in the environment' }], bank: ['sensor', 'switch', 'resistor', 'battery'], labels: { sensor: '📡 Sensor', switch: '🔘 Switch', resistor: '⬛ Resistor', battery: '🔋 Battery' } },
  { description: 'An electromagnetic switch controlled by another circuit is a...?', layout: '🧲 —?', blanks: [{ position: 0, correctComponent: 'relay', emoji: '🧲', hint: 'Uses an electromagnet to switch a circuit' }], bank: ['relay', 'diode', 'sensor', 'switch'], labels: { relay: '🧲 Relay', diode: '➡️ Diode', sensor: '📡 Sensor', switch: '🔘 Switch' } },
  { description: 'A switch you press and release, used on a doorbell, is a...?', layout: '🔲 —?', blanks: [{ position: 0, correctComponent: 'push button', emoji: '🔲', hint: 'Momentary contact switch' }], bank: ['push button', 'two-way switch', 'relay', 'diode'], labels: { 'push button': '🔲 Push button', 'two-way switch': '🔀 Two-way switch', relay: '🧲 Relay', diode: '➡️ Diode' } },
  { description: 'A component that stores a small electric charge temporarily is a...?', layout: '🔋 —?', blanks: [{ position: 0, correctComponent: 'capacitor', emoji: '🔋', hint: 'Stores charge, unlike a resistor' }], bank: ['capacitor', 'resistor', 'diode', 'switch'], labels: { capacitor: '🔋 Capacitor', resistor: '⬛ Resistor', diode: '➡️ Diode', switch: '🔘 Switch' } },
  { description: 'A motion-activated security light uses which type of component to detect movement?', layout: '💡(motion) —?', blanks: [{ position: 0, correctComponent: 'sensor', emoji: '📡', hint: 'Detects the motion to trigger the light' }], bank: ['sensor', 'diode', 'capacitor', 'relay'], labels: { sensor: '📡 Sensor', diode: '➡️ Diode', capacitor: '🔋 Capacitor', relay: '🧲 Relay' } },
  { description: 'What switching component protects a circuit by automatically breaking it when current is too high?', layout: '⚡(overload) —?', blanks: [{ position: 0, correctComponent: 'circuit breaker', emoji: '🛑', hint: 'Trips to stop dangerous overloads' }], bank: ['circuit breaker', 'diode', 'capacitor', 'push button'], labels: { 'circuit breaker': '🛑 Circuit breaker', diode: '➡️ Diode', capacitor: '🔋 Capacitor', 'push button': '🔲 Push button' } },
  { description: 'A device that converts electrical signals into sound is a...?', layout: '⚡ —?— 🔊', blanks: [{ position: 0, correctComponent: 'buzzer', emoji: '🔔', hint: 'Turns current into sound' }], bank: ['buzzer', 'sensor', 'diode', 'relay'], labels: { buzzer: '🔔 Buzzer', sensor: '📡 Sensor', diode: '➡️ Diode', relay: '🧲 Relay' } },
]);

module.exports = { TOPICS };
