#!/usr/bin/env node
'use strict';

/**
 * Phase B — regenerates lib/core/constants/game_catalog.dart from
 * topics.json, and scaffolds any missing assets/content/**\/*.json content
 * packs. Safe to re-run: catalog regeneration is a full deterministic
 * rewrite; content packs are only scaffolded when the file doesn't already
 * exist, so Phase C's authored content is never clobbered.
 */

const fs = require('fs');
const path = require('path');
const { dartString, dartList } = require('./dart_format');

const ROOT = path.join(__dirname, '../..');
const TOPICS_PATH = path.join(__dirname, 'topics.json');
const CATALOG_OUT = path.join(ROOT, 'lib/core/constants/game_catalog.dart');
const PUBSPEC_PATH = path.join(ROOT, 'pubspec.yaml');

const GRADE_BAND_LABEL = {
  grade1: 'FOUNDATION PHASE — GRADES 1–3',
  grade4: 'INTERMEDIATE PHASE — GRADES 4–6',
  grade7: 'SENIOR PHASE — GRADES 7–9',
};
const GRADE_ORDER = ['grade1', 'grade4', 'grade7'];
const SUBJECT_ORDER = {
  grade1: ['Mathematics', 'English', 'Life Skills'],
  grade4: ['Mathematics', 'Natural Sciences', 'Social Sciences', 'English', 'Life Skills'],
  grade7: [
    'Mathematics',
    'English',
    'Life Skills',
    'Social Sciences',
    'Natural Sciences',
    'Technology',
    'EMS',
  ],
};

function subjectIndex(grade, subject) {
  const order = SUBJECT_ORDER[grade] || [];
  const i = order.indexOf(subject);
  return i === -1 ? order.length : i;
}

function emitEntry(t) {
  const flags = [];
  if (t.isNew) flags.push('isNew: true');
  if (t.isFeatured) flags.push('isFeatured: true');
  const flagsStr = flags.length ? ` ${flags.join(', ')},` : '';
  return `    GameCatalogEntry(
      id: ${dartString(t.id)},
      title: ${dartString(t.title)},
      description: ${dartString(t.description)},
      grade: ${dartString(t.grade)}, grades: ${dartList(t.grades)},
      subject: ${dartString(t.subject)}, topicId: ${dartString(t.topicId)}, subtopicId: ${dartString(t.subtopicId)},
      engineType: ${dartString(t.engine)}, emoji: ${dartString(t.emoji)}, color: ${t.colorExpr},
      learningObjective: ${dartString(t.capsObjective)},
      mechanicReason: ${dartString(t.mechanicReason)},
      difficulty: ${dartString(t.difficulty.label)}, xpReward: ${t.xpReward}, coinsReward: ${t.coinsReward},${flagsStr}
    ),`;
}

function generateCatalogDart(topics) {
  const byGrade = new Map();
  for (const t of topics) {
    if (!byGrade.has(t.grade)) byGrade.set(t.grade, []);
    byGrade.get(t.grade).push(t);
  }

  const sections = [];
  for (const grade of GRADE_ORDER) {
    const gradeTopics = byGrade.get(grade) || [];
    if (gradeTopics.length === 0) continue;

    const bySubject = new Map();
    for (const t of gradeTopics) {
      if (!bySubject.has(t.subject)) bySubject.set(t.subject, []);
      bySubject.get(t.subject).push(t);
    }
    const subjects = [...bySubject.keys()].sort(
      (a, b) => subjectIndex(grade, a) - subjectIndex(grade, b)
    );

    const bar = '═'.repeat(75);
    let section = `    // ${bar}\n    // ${GRADE_BAND_LABEL[grade]}\n    // ${bar}\n`;
    for (const subject of subjects) {
      const entries = bySubject.get(subject).sort((a, b) => a.sourceOrder - b.sourceOrder);
      const dash = '─'.repeat(Math.max(3, 74 - subject.length - 12));
      section += `\n    // ${subject.toUpperCase()} (${entries.length} games) ${dash}\n`;
      section += entries.map(emitEntry).join('\n') + '\n';
    }
    sections.push(section);
  }

  return `// GENERATED by tools/gamegen — edit topics.json (and classify.js /
// difficulty.js / phrasing.js), not this file. Regenerate with:
//   node tools/gamegen/generate.js
import 'package:flutter/material.dart';
import 'package:questkids/core/theme/app_colors.dart';

class GameCatalogEntry {
  final String id;
  final String title;
  final String description;
  final String grade;
  final List<String> grades;
  final String subject;
  final String topicId;
  final String subtopicId;
  final String engineType;
  final String emoji;
  final Color color;
  /// CAPS-phrased learning outcome shown to the learner before they play.
  final String learningObjective;
  /// One child-readable sentence explaining why this engine's mechanic
  /// teaches this particular skill.
  final String mechanicReason;
  final String difficulty;
  final int xpReward;
  final int coinsReward;
  final bool isNew;
  final bool isFeatured;
  final Map<String, dynamic> extras;

  const GameCatalogEntry({
    required this.id,
    required this.title,
    required this.description,
    required this.grade,
    required this.grades,
    required this.subject,
    required this.topicId,
    required this.subtopicId,
    required this.engineType,
    required this.emoji,
    required this.color,
    required this.learningObjective,
    required this.mechanicReason,
    required this.difficulty,
    required this.xpReward,
    required this.coinsReward,
    this.isNew = false,
    this.isFeatured = false,
    this.extras = const {},
  });
}

class GameCatalog {
  static const List<GameCatalogEntry> all = [
${sections.join('\n')}
  ];

  static List<GameCatalogEntry> forGrade(String grade) =>
      all.where((e) => e.grades.contains(grade) || e.grades.contains('all')).toList();

  static List<GameCatalogEntry> forSubject(String subject, String grade) =>
      forGrade(grade).where((e) => e.subject == subject).toList();

  static List<GameCatalogEntry> featured(String grade) =>
      forGrade(grade).where((e) => e.isFeatured).toList();
}
`;
}

// ── Content pack scaffolding ────────────────────────────────────────────

function scaffoldFor(t) {
  const common = {
    id: t.id,
    engine: t.engine,
    grade: t.grade,
    subject: t.subject,
    title: t.title,
    tagline: t.description,
    accentColorHex: '#5C35F5',
    emoji: t.emoji,
    _scaffold: true,
  };
  switch (t.engine) {
    case 'tugOfWar':
    case 'numberCountingDuel':
      return { ...common, questionType: 'addition', sampleItems: [] };
    case 'adventureJourney':
      return { ...common, characterEmoji: t.emoji, stages: [] };
    case 'runnerCollector':
      return { ...common, levels: [] };
    case 'explorerMap':
      return { ...common, pins: [], questions: [] };
    case 'sequenceBuilder':
      return { ...common, sceneType: t.topicId, steps: [], roundVariants: [] };
    case 'circuitBuilder':
      return { ...common, circuits: [] };
    case 'budgetBuilder':
      return { ...common, scenarios: [] };
    case 'multiplesMerge':
      return { ...common, mode: 'numeric', gridSize: 4, chainLength: 4, tables: [] };
    default:
      throw new Error(`no scaffold shape for engine "${t.engine}"`);
  }
}

function writeScaffolds(topics) {
  let created = 0;
  for (const t of topics) {
    const outPath = path.join(ROOT, t.contentPack);
    if (fs.existsSync(outPath)) continue;
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, JSON.stringify(scaffoldFor(t), null, 2) + '\n');
    created++;
  }
  return created;
}

function ensurePubspecAssetRegistered() {
  const text = fs.readFileSync(PUBSPEC_PATH, 'utf8');
  if (text.includes('assets/content/')) return false;
  const updated = text.replace(
    /(\n\s*assets:\n)/,
    `$1    - assets/content/\n`
  );
  if (updated === text) {
    throw new Error('could not find `assets:` section in pubspec.yaml to register assets/content/');
  }
  fs.writeFileSync(PUBSPEC_PATH, updated);
  return true;
}

function main() {
  const topics = JSON.parse(fs.readFileSync(TOPICS_PATH, 'utf8'));

  fs.writeFileSync(CATALOG_OUT, generateCatalogDart(topics));
  console.log(`Wrote ${path.relative(ROOT, CATALOG_OUT)} (${topics.length} entries).`);

  const created = writeScaffolds(topics);
  console.log(`Scaffolded ${created} new content pack(s) under assets/content/ (existing packs untouched).`);

  const registered = ensurePubspecAssetRegistered();
  console.log(registered ? 'Registered assets/content/ in pubspec.yaml.' : 'assets/content/ already registered in pubspec.yaml.');
}

main();
