// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // Firebase has no native Linux SDK; reuse the web app config
        // (same approach the FlutterFire CLI uses for Windows).
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMH4vPHX9ohTaK6HQSB4sCUE10C6oPNCY',
    appId: '1:882077922348:web:130f4b96e9d2122fa5cd89',
    messagingSenderId: '882077922348',
    projectId: 'questkids-mobile',
    authDomain: 'questkids-mobile.firebaseapp.com',
    storageBucket: 'questkids-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCim0gC3W6HJFiu8fdB27a7MhBV3PI6SRo',
    appId: '1:882077922348:android:80ef355749cb38f1a5cd89',
    messagingSenderId: '882077922348',
    projectId: 'questkids-mobile',
    storageBucket: 'questkids-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRlwfhPI5ScwH8WqLVrXhiibm3SssmLE',
    appId: '1:882077922348:ios:47caa192c020c507a5cd89',
    messagingSenderId: '882077922348',
    projectId: 'questkids-mobile',
    storageBucket: 'questkids-mobile.firebasestorage.app',
    iosBundleId: 'com.questkids.questkids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRlwfhPI5ScwH8WqLVrXhiibm3SssmLE',
    appId: '1:882077922348:ios:47caa192c020c507a5cd89',
    messagingSenderId: '882077922348',
    projectId: 'questkids-mobile',
    storageBucket: 'questkids-mobile.firebasestorage.app',
    iosBundleId: 'com.questkids.questkids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMH4vPHX9ohTaK6HQSB4sCUE10C6oPNCY',
    appId: '1:882077922348:web:6193d75972217258a5cd89',
    messagingSenderId: '882077922348',
    projectId: 'questkids-mobile',
    authDomain: 'questkids-mobile.firebaseapp.com',
    storageBucket: 'questkids-mobile.firebasestorage.app',
  );
}
