import 'package:flutter/material.dart';

class GameCatalogEntry {
  final String id;
  final String title;
  final String description;
  final String grade;
  final List<String> grades;
  final String subject;
  final String topicId;
  final String subtopicId;
  final String engineType;
  final String emoji;
  final Color color;
  final String difficulty;
  final int xpReward;
  final int coinsReward;
  final bool isNew;
  final bool isFeatured;
  final Map<String, dynamic> extras;

  const GameCatalogEntry({
    required this.id,
    required this.title,
    required this.description,
    required this.grade,
    required this.grades,
    required this.subject,
    required this.topicId,
    required this.subtopicId,
    required this.engineType,
    required this.emoji,
    required this.color,
    required this.difficulty,
    required this.xpReward,
    required this.coinsReward,
    this.isNew = false,
    this.isFeatured = false,
    this.extras = const {},
  });
}

class GameCatalog {
  static const List<GameCatalogEntry> all = [

    // ═══════════════════════════════════════════════════════════════════════════
    // FOUNDATION PHASE — GRADE 1
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g1_counting',
      title: 'Number Counting Duel',
      description: 'Count and compare numbers 1–20 in a battle against the AI!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Mathematics', topicId: 'numbers', subtopicId: 'counting',
      engineType: 'tugOfWar', emoji: '🔢', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 50, coinsReward: 10, isFeatured: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 5},
    ),
    GameCatalogEntry(
      id: 'math_g1_shapes',
      title: 'Shape Showdown',
      description: 'Name and match 2D shapes — circles, squares, triangles and more!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Mathematics', topicId: 'geometry', subtopicId: '2d_shapes',
      engineType: 'adventureJourney', emoji: '🔷', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'shapes'},
    ),
    GameCatalogEntry(
      id: 'math_g1_ordering',
      title: 'Number Order Quest',
      description: 'Place numbers in the correct order from 1 to 20!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Mathematics', topicId: 'numbers', subtopicId: 'ordering',
      engineType: 'sequenceBuilder', emoji: '1️⃣', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'math_g1_addition_simple',
      title: 'Add It Up!',
      description: 'Add small numbers and win the tug of war!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'addition_simple',
      engineType: 'tugOfWar', emoji: '➕', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'multiplierMin': 1, 'multiplierMax': 5},
    ),
    GameCatalogEntry(
      id: 'math_g1_money',
      title: 'Coin Count',
      description: 'Identify and count South African coins in everyday life!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Mathematics', topicId: 'money', subtopicId: 'recognise_coins',
      engineType: 'adventureJourney', emoji: '🪙', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'stages': 4, 'theme': 'market'},
    ),

    // ENGLISH ─────────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g1_letters',
      title: 'Letter Land',
      description: 'Run through Letter Land collecting alphabet letters and phonics!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'English', topicId: 'phonics', subtopicId: 'alphabet_phonics',
      engineType: 'runnerCollector', emoji: '🔤', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 50, coinsReward: 10, isFeatured: true,
      extras: {'speed': 1.0, 'collectMode': 'letters'},
    ),
    GameCatalogEntry(
      id: 'eng_g1_phonics',
      title: 'Sound Safari',
      description: 'Identify beginning sounds and match them to pictures!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'English', topicId: 'phonics', subtopicId: 'beginning_sounds',
      engineType: 'adventureJourney', emoji: '🗣️', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'safari'},
    ),
    GameCatalogEntry(
      id: 'eng_g1_sight_words',
      title: 'Sight Word Sprint',
      description: 'Collect common sight words as you run through Word World!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'English', topicId: 'reading', subtopicId: 'sight_words',
      engineType: 'runnerCollector', emoji: '👁️', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'speed': 0.9, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g1_body_words',
      title: 'Body Parts Dash',
      description: 'Learn body part words as you race through the adventure!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'English', topicId: 'vocabulary', subtopicId: 'body_parts',
      engineType: 'runnerCollector', emoji: '🏃', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'speed': 0.8, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g1_colours',
      title: 'Colour Collector',
      description: 'Collect colour words and match them to their colours!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'English', topicId: 'vocabulary', subtopicId: 'colours',
      engineType: 'runnerCollector', emoji: '🎨', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'speed': 0.8, 'collectMode': 'words'},
    ),

    // LIFE SKILLS — Grade 1 ───────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ls_g1_personal_care',
      title: 'Morning Routine Hero',
      description: 'Put your morning routine in the right order to become a Life Skills hero!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Life Skills', topicId: 'personal_care', subtopicId: 'morning_routine',
      engineType: 'sequenceBuilder', emoji: '🦷', color: Color(0xFFFF9800),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'ls_g1_emotions',
      title: 'Feelings Journey',
      description: 'Explore emotions and learn healthy ways to express your feelings!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Life Skills', topicId: 'social_skills', subtopicId: 'emotions',
      engineType: 'adventureJourney', emoji: '😊', color: Color(0xFFFF9800),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'stages': 5, 'theme': 'emotions'},
    ),
    GameCatalogEntry(
      id: 'ls_g1_safety',
      title: 'Safety First!',
      description: 'Learn the rules of road safety and being safe at home!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Life Skills', topicId: 'safety', subtopicId: 'personal_safety',
      engineType: 'adventureJourney', emoji: '🚦', color: Color(0xFFFF9800),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'stages': 4, 'theme': 'safety'},
    ),
    GameCatalogEntry(
      id: 'ls_g1_movement',
      title: 'Movement Master',
      description: 'Learn basic body movements and physical exercises!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Life Skills', topicId: 'physical_education', subtopicId: 'body_movement',
      engineType: 'adventureJourney', emoji: '🤸', color: Color(0xFFFF9800),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'playground'},
    ),
    GameCatalogEntry(
      id: 'ls_g1_community',
      title: 'Community Helper',
      description: 'Discover the helpers in our community and what they do!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Life Skills', topicId: 'beginning_knowledge', subtopicId: 'community_helpers',
      engineType: 'explorerMap', emoji: '👮', color: Color(0xFFFF9800),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'mapScale': 'local', 'pinCount': 6},
    ),

    // NATURAL SCIENCES — Grade 1 ──────────────────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g1_animals',
      title: 'Animal Safari',
      description: 'Journey through the wild and classify mammals, birds and reptiles!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Natural Sciences', topicId: 'animals', subtopicId: 'animal_classification',
      engineType: 'adventureJourney', emoji: '🦁', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 50, coinsReward: 10, isFeatured: true,
      extras: {'stages': 4, 'theme': 'safari'},
    ),
    GameCatalogEntry(
      id: 'sci_g1_weather',
      title: 'Weather Watcher',
      description: 'Learn about different types of weather and seasons!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Natural Sciences', topicId: 'weather', subtopicId: 'weather_types',
      engineType: 'adventureJourney', emoji: '⛅', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'weather'},
    ),
    GameCatalogEntry(
      id: 'sci_g1_senses',
      title: 'Five Senses Quest',
      description: 'Explore the world through your five amazing senses!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Natural Sciences', topicId: 'senses', subtopicId: 'five_senses',
      engineType: 'adventureJourney', emoji: '👂', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 5, 'theme': 'senses'},
    ),
    GameCatalogEntry(
      id: 'sci_g1_plants',
      title: 'Plant Detective',
      description: 'Find and identify common plants in your environment!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Natural Sciences', topicId: 'plants', subtopicId: 'common_plants',
      engineType: 'adventureJourney', emoji: '🌻', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'garden'},
    ),
    GameCatalogEntry(
      id: 'sci_g1_materials',
      title: 'Material Explorer',
      description: 'Discover different materials and their properties around you!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Natural Sciences', topicId: 'materials', subtopicId: 'material_properties',
      engineType: 'adventureJourney', emoji: '🪨', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'workshop'},
    ),

    // SOCIAL SCIENCES — Grade 1 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g1_community',
      title: 'My Community Map',
      description: 'Explore your local community and pin its amazing features!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Social Sciences', topicId: 'community', subtopicId: 'local_community',
      engineType: 'explorerMap', emoji: '🏘️', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'mapScale': 'local', 'pinCount': 6},
    ),
    GameCatalogEntry(
      id: 'ssc_g1_family',
      title: 'Family Adventure',
      description: 'Learn about different family types and family roles!',
      grade: 'grade1', grades: ['grade1'],
      subject: 'Social Sciences', topicId: 'family', subtopicId: 'family_types',
      engineType: 'adventureJourney', emoji: '👨‍👩‍👧', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 45, coinsReward: 9,
      extras: {'stages': 4, 'theme': 'home'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // FOUNDATION PHASE — GRADE 2
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g2_addition',
      title: 'Addition Adventure',
      description: 'Add numbers up to 50 and outpull your rival!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'addition',
      engineType: 'tugOfWar', emoji: '➕', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 60, coinsReward: 12, isFeatured: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'math_g2_subtraction',
      title: 'Subtraction Battle',
      description: 'Subtract numbers and pull the rope to victory!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'subtraction',
      engineType: 'tugOfWar', emoji: '➖', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 60, coinsReward: 12,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'math_g2_doubles',
      title: 'Doubles Dash',
      description: 'Master doubles in this exciting number adventure!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'doubles',
      engineType: 'tugOfWar', emoji: '2️⃣', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'math_g2_place_value',
      title: 'Place Value Power',
      description: 'Discover tens and units by placing numbers in the right place!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Mathematics', topicId: 'numbers', subtopicId: 'place_value',
      engineType: 'sequenceBuilder', emoji: '🔟', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'math_g2_time',
      title: 'Time Trekker',
      description: 'Learn to read clocks and understand time!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Mathematics', topicId: 'time', subtopicId: 'reading_clocks',
      engineType: 'adventureJourney', emoji: '⏰', color: Color(0xFFFF6B35),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'stages': 5, 'theme': 'clock_tower'},
    ),

    // ENGLISH — Grade 2 ───────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g2_words',
      title: 'Word Wizard',
      description: 'Sprint and collect simple words to build amazing sentences!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'English', topicId: 'vocabulary', subtopicId: 'simple_words',
      engineType: 'runnerCollector', emoji: '✨', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 60, coinsReward: 12, isFeatured: true,
      extras: {'speed': 1.2, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g2_sentence',
      title: 'Sentence Builder',
      description: 'Arrange words in the correct order to build proper sentences!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'English', topicId: 'writing', subtopicId: 'sentences',
      engineType: 'sequenceBuilder', emoji: '📝', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'eng_g2_nouns',
      title: 'Noun Hunter',
      description: 'Hunt and collect nouns — people, places and things!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'English', topicId: 'grammar', subtopicId: 'nouns',
      engineType: 'runnerCollector', emoji: '🔍', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'speed': 1.0, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g2_rhymes',
      title: 'Rhyme Runner',
      description: 'Collect rhyming word pairs as you sprint through rhyme world!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'English', topicId: 'phonics', subtopicId: 'rhyming',
      engineType: 'runnerCollector', emoji: '🎵', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'speed': 1.0, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g2_punctuation_basic',
      title: 'Punctuation Picker',
      description: 'Pick the right punctuation marks to complete sentences!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'English', topicId: 'punctuation', subtopicId: 'basic_punctuation',
      engineType: 'runnerCollector', emoji: '❓', color: Color(0xFFE91E63),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'speed': 1.0, 'collectMode': 'punctuation'},
    ),

    // NATURAL SCIENCES — Grade 2 ──────────────────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g2_plants',
      title: 'Plant Life Journey',
      description: 'Follow a seed through its incredible plant growth stages!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Natural Sciences', topicId: 'plants', subtopicId: 'growth_stages',
      engineType: 'adventureJourney', emoji: '🌱', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 60, coinsReward: 12, isFeatured: true,
      extras: {'stages': 5, 'theme': 'garden'},
    ),
    GameCatalogEntry(
      id: 'sci_g2_insects',
      title: 'Bug Explorer',
      description: 'Discover amazing insects and learn about their life cycles!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Natural Sciences', topicId: 'animals', subtopicId: 'insects',
      engineType: 'adventureJourney', emoji: '🐛', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'stages': 4, 'theme': 'garden'},
    ),
    GameCatalogEntry(
      id: 'sci_g2_soil',
      title: 'Soil Science',
      description: 'Dig into soil and discover what lives beneath the ground!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Natural Sciences', topicId: 'environment', subtopicId: 'soil',
      engineType: 'adventureJourney', emoji: '🌍', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 50, coinsReward: 10,
      extras: {'stages': 4, 'theme': 'underground'},
    ),

    // SOCIAL SCIENCES — Grade 2 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g2_neighbourhood',
      title: 'Neighbourhood Explorer',
      description: 'Map transport routes and find community helpers in your area!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Social Sciences', topicId: 'neighbourhood', subtopicId: 'transport_helpers',
      engineType: 'explorerMap', emoji: '🚌', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 60, coinsReward: 12,
      extras: {'mapScale': 'neighbourhood', 'pinCount': 8},
    ),
    GameCatalogEntry(
      id: 'ssc_g2_past_present',
      title: 'Past and Present',
      description: 'Compare how life has changed from the past to today!',
      grade: 'grade2', grades: ['grade2'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'past_present',
      engineType: 'adventureJourney', emoji: '⏳', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 55, coinsReward: 11,
      extras: {'stages': 4, 'theme': 'time_travel'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // FOUNDATION PHASE — GRADE 3
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g3_tables',
      title: 'Multiples Merge: Rookie',
      description: 'Connect the multiples of 3, 4, 6 & 8 in order and watch them merge!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Mathematics', topicId: 'multiplication', subtopicId: 'tables_2_5',
      engineType: 'multiplesMerge', emoji: '✖️', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 80, coinsReward: 15, isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 5},
    ),
    GameCatalogEntry(
      id: 'math_g3_division',
      title: 'Division Duel',
      description: 'Master simple division and defeat the AI champion!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'division_basic',
      engineType: 'tugOfWar', emoji: '➗', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 75, coinsReward: 15,
      extras: {'multiplierMin': 2, 'multiplierMax': 5},
    ),
    GameCatalogEntry(
      id: 'math_g3_fractions_basic',
      title: 'Fraction Finder',
      description: 'Find and identify basic fractions: halves, thirds and quarters!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Mathematics', topicId: 'fractions', subtopicId: 'halves_quarters',
      engineType: 'adventureJourney', emoji: '🍕', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 75, coinsReward: 15,
      extras: {'stages': 5, 'theme': 'pizza_party'},
    ),
    GameCatalogEntry(
      id: 'math_g3_measurement',
      title: 'Measurement Mission',
      description: 'Measure lengths using centimetres and metres!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Mathematics', topicId: 'measurement', subtopicId: 'length',
      engineType: 'adventureJourney', emoji: '📏', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'stages': 5, 'theme': 'builder'},
    ),
    GameCatalogEntry(
      id: 'math_g3_patterns',
      title: 'Pattern Power',
      description: 'Find, describe and extend number and shape patterns!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Mathematics', topicId: 'patterns', subtopicId: 'number_patterns',
      engineType: 'sequenceBuilder', emoji: '🔁', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'stages': 5},
    ),

    // ENGLISH — Grade 3 ───────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g3_story',
      title: 'Story Builder',
      description: 'Dash through stories collecting vocabulary and reading gems!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'English', topicId: 'reading', subtopicId: 'vocabulary_reading',
      engineType: 'runnerCollector', emoji: '📚', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 75, coinsReward: 15, isFeatured: true,
      extras: {'speed': 1.4, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g3_adjectives',
      title: 'Adjective Adventure',
      description: 'Collect describing words and make your writing come alive!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'English', topicId: 'grammar', subtopicId: 'adjectives',
      engineType: 'runnerCollector', emoji: '🌈', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'speed': 1.2, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g3_verbs',
      title: 'Verb Velocity',
      description: 'Race and collect action words (verbs) in this fast-paced run!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'English', topicId: 'grammar', subtopicId: 'verbs',
      engineType: 'runnerCollector', emoji: '🏃‍♂️', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'speed': 1.3, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g3_comprehension',
      title: 'Reading Ranger',
      description: 'Read a short passage and collect the correct comprehension answers!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'English', topicId: 'reading', subtopicId: 'comprehension',
      engineType: 'adventureJourney', emoji: '📖', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 75, coinsReward: 15,
      extras: {'stages': 5, 'theme': 'library'},
    ),
    GameCatalogEntry(
      id: 'eng_g3_spelling',
      title: 'Spelling Sprint',
      description: 'Race against time to collect correctly spelled words!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'English', topicId: 'spelling', subtopicId: 'word_families',
      engineType: 'runnerCollector', emoji: '✅', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'speed': 1.2, 'collectMode': 'words'},
    ),

    // NATURAL SCIENCES — Grade 3 ──────────────────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g3_nutrition',
      title: 'Food & Nutrition Quest',
      description: 'Explore healthy and unhealthy foods on an epic quest!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Natural Sciences', topicId: 'nutrition', subtopicId: 'healthy_foods',
      engineType: 'adventureJourney', emoji: '🥦', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 70, coinsReward: 14,
      extras: {'stages': 4, 'theme': 'kitchen'},
    ),
    GameCatalogEntry(
      id: 'sci_g3_water',
      title: 'Water Warriors',
      description: 'Explore the importance of water and learn to save it!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Natural Sciences', topicId: 'water', subtopicId: 'water_importance',
      engineType: 'adventureJourney', emoji: '💧', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 65, coinsReward: 13,
      extras: {'stages': 4, 'theme': 'water'},
    ),
    GameCatalogEntry(
      id: 'sci_g3_habitats',
      title: 'Habitat Hunt',
      description: 'Discover the amazing habitats that animals call home!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Natural Sciences', topicId: 'animals', subtopicId: 'habitats',
      engineType: 'adventureJourney', emoji: '🦎', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 70, coinsReward: 14,
      extras: {'stages': 5, 'theme': 'wilderness'},
    ),

    // SOCIAL SCIENCES — Grade 3 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g3_history',
      title: 'Local History Quest',
      description: "Journey through South Africa's early history on an interactive map!",
      grade: 'grade3', grades: ['grade3'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'sa_early_history',
      engineType: 'explorerMap', emoji: '🏛️', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 70, coinsReward: 14,
      extras: {'mapScale': 'country', 'pinCount': 8},
    ),
    GameCatalogEntry(
      id: 'ssc_g3_culture',
      title: 'Culture Explorer',
      description: 'Discover the diverse cultures and traditions of South Africa!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Social Sciences', topicId: 'culture', subtopicId: 'sa_cultures',
      engineType: 'adventureJourney', emoji: '🎭', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 65, coinsReward: 13,
      extras: {'stages': 5, 'theme': 'culture'},
    ),
    GameCatalogEntry(
      id: 'ssc_g3_environment',
      title: 'Environment Explorer',
      description: 'Explore natural environments and learn to protect them!',
      grade: 'grade3', grades: ['grade3'],
      subject: 'Social Sciences', topicId: 'environment', subtopicId: 'natural_environments',
      engineType: 'explorerMap', emoji: '🌿', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 65, coinsReward: 13,
      extras: {'mapScale': 'country', 'pinCount': 6},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // INTERMEDIATE PHASE — GRADE 4
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g4_multiplication',
      title: 'Multiples Merge',
      description: 'Trace a glowing path through the multiples — then prove it in the Weekly Quiz!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'multiplication', subtopicId: 'tables_2_12',
      engineType: 'multiplesMerge', emoji: '🧮', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g4_division',
      title: 'Division Duel Advanced',
      description: 'Master long division in this intense tug of war battle!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'division',
      engineType: 'tugOfWar', emoji: '➗', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 95, coinsReward: 19,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g4_fractions',
      title: 'Fraction Frenzy',
      description: 'Compare and order fractions in this exciting challenge!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'fractions', subtopicId: 'fractions_order',
      engineType: 'sequenceBuilder', emoji: '🍕', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'math_g4_geometry',
      title: '3D Shape Expedition',
      description: 'Explore 3D shapes and their properties in this space adventure!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'geometry', subtopicId: '3d_shapes',
      engineType: 'adventureJourney', emoji: '📦', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5, 'theme': 'space'},
    ),
    GameCatalogEntry(
      id: 'math_g4_data',
      title: 'Data Detective',
      description: 'Collect and organise data, then read graphs and tables!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'data', subtopicId: 'graphs_tables',
      engineType: 'adventureJourney', emoji: '📊', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5, 'theme': 'detective'},
    ),
    GameCatalogEntry(
      id: 'math_g4_area',
      title: 'Area Arena',
      description: 'Calculate the area of rectangles and squares!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'measurement', subtopicId: 'area',
      engineType: 'tugOfWar', emoji: '📐', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'multiplierMin': 1, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g4_number_sentences',
      title: 'Number Sentence Ninja',
      description: 'Build and solve number sentences using all four operations!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'operations', subtopicId: 'number_sentences',
      engineType: 'tugOfWar', emoji: '🥷', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 95, coinsReward: 19,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g4_word_problems',
      title: 'Word Problem Warrior',
      description: 'Solve real-world word problems and conquer the challenge!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'problem_solving', subtopicId: 'word_problems',
      engineType: 'adventureJourney', emoji: '🧠', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 95, coinsReward: 19,
      extras: {'stages': 6, 'theme': 'adventure'},
    ),
    GameCatalogEntry(
      id: 'math_g4_money',
      title: 'Money Market',
      description: 'Use SA money to buy, sell and calculate change!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'money', subtopicId: 'calculate_change',
      engineType: 'adventureJourney', emoji: '💰', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'stages': 5, 'theme': 'market'},
    ),
    GameCatalogEntry(
      id: 'math_g4_patterns',
      title: 'Pattern Master',
      description: 'Create, describe and extend number patterns and sequences!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Mathematics', topicId: 'patterns', subtopicId: 'number_sequences',
      engineType: 'sequenceBuilder', emoji: '🔢', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 6},
    ),

    // ENGLISH — Grade 4 ───────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g4_grammar',
      title: 'Grammar Hero Run',
      description: 'Race and collect nouns, verbs and adjectives — become a grammar hero!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'grammar', subtopicId: 'parts_of_speech',
      engineType: 'runnerCollector', emoji: '🦸', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 90, coinsReward: 18, isFeatured: true,
      extras: {'speed': 1.6, 'collectMode': 'partsOfSpeech'},
    ),
    GameCatalogEntry(
      id: 'eng_g4_reading',
      title: 'Reading Quest',
      description: 'Read passages and answer comprehension questions!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'reading', subtopicId: 'comprehension',
      engineType: 'adventureJourney', emoji: '📖', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 6, 'theme': 'library'},
    ),
    GameCatalogEntry(
      id: 'eng_g4_synonyms',
      title: 'Synonym Sprinter',
      description: 'Find words with the same meaning as you race through synonym city!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'vocabulary', subtopicId: 'synonyms',
      engineType: 'runnerCollector', emoji: '🔄', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'speed': 1.4, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g4_tenses',
      title: 'Tense Tracker',
      description: 'Identify past, present and future tenses in action!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'grammar', subtopicId: 'tenses',
      engineType: 'runnerCollector', emoji: '⏰', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'speed': 1.5, 'collectMode': 'tenses'},
    ),
    GameCatalogEntry(
      id: 'eng_g4_creative_writing',
      title: 'Story Starter',
      description: 'Order story elements — beginning, middle and end — into the correct sequence!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'writing', subtopicId: 'creative_writing',
      engineType: 'sequenceBuilder', emoji: '✍️', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'eng_g4_visual_text',
      title: 'Visual Text Explorer',
      description: 'Explore posters, charts and other visual texts to find information!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'English', topicId: 'reading', subtopicId: 'visual_texts',
      engineType: 'adventureJourney', emoji: '🖼️', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 80, coinsReward: 16,
      extras: {'stages': 5, 'theme': 'gallery'},
    ),

    // NATURAL SCIENCES & TECHNOLOGY — Grade 4 ─────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g4_water',
      title: 'Water Cycle Adventure',
      description: 'Learn the cycle, then drag the stages into the right order to make it rain!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Natural Sciences', topicId: 'water', subtopicId: 'water_cycle',
      engineType: 'sequenceBuilder', emoji: '💧', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 90, coinsReward: 18, isFeatured: true,
      extras: {'stages': 6, 'theme': 'weather'},
    ),
    GameCatalogEntry(
      id: 'sci_g4_food_chains',
      title: 'Food Chain Frenzy',
      description: 'Build food chains and discover who eats who in nature!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Natural Sciences', topicId: 'ecology', subtopicId: 'food_chains',
      engineType: 'sequenceBuilder', emoji: '🦁', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'sci_g4_matter',
      title: 'Matter Lab',
      description: 'Explore solids, liquids and gases in the Matter Lab!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Natural Sciences', topicId: 'matter', subtopicId: 'states_of_matter',
      engineType: 'adventureJourney', emoji: '⚗️', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5, 'theme': 'laboratory'},
    ),
    GameCatalogEntry(
      id: 'sci_g4_energy',
      title: 'Energy Explorer',
      description: 'Discover different forms of energy and how they work!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Natural Sciences', topicId: 'energy', subtopicId: 'energy_forms',
      engineType: 'adventureJourney', emoji: '⚡', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5, 'theme': 'power_plant'},
    ),
    GameCatalogEntry(
      id: 'tech_g4_design_process',
      title: 'Design Challenge',
      description: 'Follow the IDMEC design process to solve a real-world problem!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Technology', topicId: 'design', subtopicId: 'design_process',
      engineType: 'sequenceBuilder', emoji: '🔧', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'stages': 5},
    ),
    GameCatalogEntry(
      id: 'tech_g4_structures',
      title: 'Structure Builder',
      description: 'Learn how structures work and what makes them strong!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Technology', topicId: 'structures', subtopicId: 'strong_structures',
      engineType: 'adventureJourney', emoji: '🏗️', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 5, 'theme': 'construction'},
    ),

    // SOCIAL SCIENCES — Grade 4 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g4_provinces',
      title: 'SA Provinces Explorer',
      description: 'Discover all 9 South African provinces, their capitals and cool facts!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'sa_provinces',
      engineType: 'explorerMap', emoji: '🗺️', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isFeatured: true,
      extras: {'mapScale': 'country', 'pinCount': 9, 'mapRegion': 'south_africa'},
    ),
    GameCatalogEntry(
      id: 'ssc_g4_map_skills',
      title: 'Map Skills Mission',
      description: 'Use compass directions and map keys to navigate South Africa!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'map_skills',
      engineType: 'explorerMap', emoji: '🧭', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'mapScale': 'country', 'pinCount': 8},
    ),
    GameCatalogEntry(
      id: 'ssc_g4_sa_history',
      title: 'SA Heritage Hunt',
      description: 'Discover key events and people in early South African history!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'sa_heritage',
      engineType: 'adventureJourney', emoji: '🏛️', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'stages': 6, 'theme': 'heritage'},
    ),
    GameCatalogEntry(
      id: 'ssc_g4_sa_resources',
      title: 'Natural Resources Race',
      description: 'Locate natural resources across the SA map and protect them!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'natural_resources',
      engineType: 'explorerMap', emoji: '💎', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 85, coinsReward: 17,
      extras: {'mapScale': 'country', 'pinCount': 8},
    ),

    // LIFE SKILLS — Grade 4 ───────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ls_g4_health',
      title: 'Health Hero',
      description: 'Learn about nutrition, hygiene and making healthy choices!',
      grade: 'grade4', grades: ['grade4'],
      subject: 'Life Skills', topicId: 'health', subtopicId: 'healthy_living',
      engineType: 'adventureJourney', emoji: '🌟', color: Color(0xFFFF9800),
      difficulty: 'medium', xpReward: 80, coinsReward: 16,
      extras: {'stages': 5, 'theme': 'health_clinic'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // INTERMEDIATE PHASE — GRADE 5
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g5_fractions',
      title: 'Fraction Faceoff',
      description: 'Compare fractions and prove who truly knows their halves!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'fractions', subtopicId: 'compare_fractions',
      engineType: 'tugOfWar', emoji: '½', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g5_decimals',
      title: 'Decimal Duel',
      description: 'Master decimals and compare them in this intense duel!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'decimals', subtopicId: 'compare_decimals',
      engineType: 'tugOfWar', emoji: '.5', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 105, coinsReward: 21,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g5_perimeter',
      title: 'Perimeter Patrol',
      description: 'Calculate perimeters of 2D shapes on this patrol mission!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'measurement', subtopicId: 'perimeter',
      engineType: 'adventureJourney', emoji: '📐', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 6, 'theme': 'city_planning'},
    ),
    GameCatalogEntry(
      id: 'math_g5_integers',
      title: 'Integer Island',
      description: 'Navigate positive and negative numbers on Integer Island!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'integers', subtopicId: 'negative_numbers',
      engineType: 'explorerMap', emoji: '🌡️', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'mapScale': 'island', 'pinCount': 10},
    ),
    GameCatalogEntry(
      id: 'math_g5_geometry',
      title: 'Angle Adventure',
      description: 'Classify and measure angles in this geometry adventure!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'geometry', subtopicId: 'angles',
      engineType: 'adventureJourney', emoji: '📐', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 6, 'theme': 'architect'},
    ),
    GameCatalogEntry(
      id: 'math_g5_proportion',
      title: 'Ratio Rumble',
      description: 'Compare ratios and solve proportion problems!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Mathematics', topicId: 'ratio', subtopicId: 'simple_ratios',
      engineType: 'tugOfWar', emoji: '⚖️', color: Color(0xFFFF6B35),
      difficulty: 'medium', xpReward: 105, coinsReward: 21,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    // ENGLISH — Grade 5 ───────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g5_tense',
      title: 'Tense Racer',
      description: 'Zoom through time collecting past, present and future tense words!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'English', topicId: 'grammar', subtopicId: 'tenses',
      engineType: 'runnerCollector', emoji: '⏱️', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isFeatured: true,
      extras: {'speed': 1.8, 'collectMode': 'tenses'},
    ),
    GameCatalogEntry(
      id: 'eng_g5_figurative',
      title: 'Figurative Language Fighter',
      description: 'Identify similes, metaphors and other figurative language!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'English', topicId: 'language', subtopicId: 'figurative_language',
      engineType: 'runnerCollector', emoji: '🦋', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 95, coinsReward: 19,
      extras: {'speed': 1.6, 'collectMode': 'words'},
    ),
    GameCatalogEntry(
      id: 'eng_g5_comprehension',
      title: 'Deep Reading Quest',
      description: 'Read and analyse texts using inference and deduction skills!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'English', topicId: 'reading', subtopicId: 'deep_comprehension',
      engineType: 'adventureJourney', emoji: '🧐', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 6, 'theme': 'detective'},
    ),
    GameCatalogEntry(
      id: 'eng_g5_essay',
      title: 'Essay Explorer',
      description: 'Plan and build essays with clear structure and good language!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'English', topicId: 'writing', subtopicId: 'essay_writing',
      engineType: 'sequenceBuilder', emoji: '📝', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 5},
    ),

    // NATURAL SCIENCES & TECHNOLOGY — Grade 5 ─────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g5_body',
      title: 'Human Body Explorer',
      description: 'Navigate the human body and discover its amazing systems and organs!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Natural Sciences', topicId: 'human_body', subtopicId: 'body_systems',
      engineType: 'adventureJourney', emoji: '🫀', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isFeatured: true,
      extras: {'stages': 7, 'theme': 'anatomy'},
    ),
    GameCatalogEntry(
      id: 'sci_g5_electricity',
      title: 'Circuit City',
      description: 'Build and test electrical circuits in the lab!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Natural Sciences', topicId: 'electricity', subtopicId: 'simple_circuits',
      engineType: 'sequenceBuilder', emoji: '💡', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 105, coinsReward: 21,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'sci_g5_diversity',
      title: 'Biodiversity Quest',
      description: 'Explore the incredible diversity of plants and animals!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Natural Sciences', topicId: 'biodiversity', subtopicId: 'plant_animal_diversity',
      engineType: 'adventureJourney', emoji: '🌿', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 6, 'theme': 'rainforest'},
    ),
    GameCatalogEntry(
      id: 'tech_g5_mechanisms',
      title: 'Mechanism Master',
      description: 'Explore gears, levers and pulleys in this engineering adventure!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Technology', topicId: 'mechanisms', subtopicId: 'gears_levers',
      engineType: 'sequenceBuilder', emoji: '⚙️', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 6},
    ),

    // SOCIAL SCIENCES — Grade 5 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g5_africa',
      title: 'African Countries',
      description: 'Pin and explore major countries across the African continent!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'african_countries',
      engineType: 'explorerMap', emoji: '🌍', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isFeatured: true,
      extras: {'mapScale': 'continent', 'pinCount': 15, 'mapRegion': 'africa'},
    ),
    GameCatalogEntry(
      id: 'ssc_g5_africa_history',
      title: 'African Kingdoms',
      description: 'Journey through great African kingdoms like Mali and Kongo!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'african_kingdoms',
      engineType: 'adventureJourney', emoji: '👑', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 105, coinsReward: 21,
      extras: {'stages': 6, 'theme': 'ancient_africa'},
    ),
    GameCatalogEntry(
      id: 'ssc_g5_climate',
      title: 'Climate Climber',
      description: 'Explore different climate zones and biomes across Africa!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'climate_zones',
      engineType: 'explorerMap', emoji: '🌡️', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'mapScale': 'continent', 'pinCount': 10},
    ),
    GameCatalogEntry(
      id: 'ssc_g5_population',
      title: 'Population Puzzle',
      description: 'Explore population distribution and human settlements in Africa!',
      grade: 'grade5', grades: ['grade5'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'population',
      engineType: 'adventureJourney', emoji: '👥', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 100, coinsReward: 20,
      extras: {'stages': 5, 'theme': 'city_planning'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // INTERMEDIATE PHASE — GRADE 6
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g6_percentages',
      title: 'Percentage Clash',
      description: 'Tackle percentages and ratios in this intense tug of war!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Mathematics', topicId: 'percentages', subtopicId: 'ratios_and_percent',
      engineType: 'tugOfWar', emoji: '%', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 130, coinsReward: 25, isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g6_algebra_intro',
      title: 'Algebra Awakening',
      description: 'Introduction to algebraic expressions and simple equations!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Mathematics', topicId: 'algebra', subtopicId: 'expressions',
      engineType: 'tugOfWar', emoji: '🔡', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 125, coinsReward: 25,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g6_volume',
      title: 'Volume Voyage',
      description: 'Calculate volume and capacity of 3D shapes!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Mathematics', topicId: 'measurement', subtopicId: 'volume_capacity',
      engineType: 'adventureJourney', emoji: '🧊', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 120, coinsReward: 24,
      extras: {'stages': 6, 'theme': 'factory'},
    ),
    GameCatalogEntry(
      id: 'math_g6_probability',
      title: 'Probability Planet',
      description: 'Explore chance and probability in this space mission!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Mathematics', topicId: 'data', subtopicId: 'probability',
      engineType: 'adventureJourney', emoji: '🎲', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 125, coinsReward: 25,
      extras: {'stages': 6, 'theme': 'space_casino'},
    ),
    GameCatalogEntry(
      id: 'math_g6_graphs',
      title: 'Graph Galaxy',
      description: 'Draw and interpret bar graphs, pie charts and line graphs!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Mathematics', topicId: 'data', subtopicId: 'graphs',
      engineType: 'adventureJourney', emoji: '📈', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 120, coinsReward: 24,
      extras: {'stages': 6, 'theme': 'data_lab'},
    ),

    // ENGLISH — Grade 6 ───────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g6_punctuation',
      title: 'Punctuation Sprint',
      description: 'Sprint through sentences and master all punctuation rules!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'English', topicId: 'punctuation', subtopicId: 'punctuation_rules',
      engineType: 'runnerCollector', emoji: '❗', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 120, coinsReward: 24, isFeatured: true,
      extras: {'speed': 2.0, 'collectMode': 'punctuation'},
    ),
    GameCatalogEntry(
      id: 'eng_g6_report_writing',
      title: 'Report Rocket',
      description: 'Master formal report writing with the correct structure!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'English', topicId: 'writing', subtopicId: 'report_writing',
      engineType: 'sequenceBuilder', emoji: '📋', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 115, coinsReward: 23,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'eng_g6_poetry',
      title: 'Poetry Sprint',
      description: 'Race through poems collecting poetic devices and literary terms!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'English', topicId: 'literature', subtopicId: 'poetry',
      engineType: 'runnerCollector', emoji: '🎭', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 115, coinsReward: 23,
      extras: {'speed': 1.8, 'collectMode': 'words'},
    ),

    // NATURAL SCIENCES & TECHNOLOGY — Grade 6 ─────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g6_ecosystem',
      title: 'Ecosystem Explorer',
      description: "Discover biomes and food chains across Earth's ecosystems!",
      grade: 'grade6', grades: ['grade6'],
      subject: 'Natural Sciences', topicId: 'ecosystems', subtopicId: 'biomes_food_chains',
      engineType: 'adventureJourney', emoji: '🌿', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 120, coinsReward: 24, isFeatured: true,
      extras: {'stages': 6, 'theme': 'wilderness'},
    ),
    GameCatalogEntry(
      id: 'sci_g6_reproduction',
      title: 'Life Cycle Lab',
      description: 'Explore reproduction and life cycles of plants and animals!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Natural Sciences', topicId: 'reproduction', subtopicId: 'life_cycles',
      engineType: 'sequenceBuilder', emoji: '🥚', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'sci_g6_acids',
      title: 'Acid & Base Battle',
      description: 'Test substances and classify them as acids or bases!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Natural Sciences', topicId: 'matter', subtopicId: 'acids_bases',
      engineType: 'tugOfWar', emoji: '🧪', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 125, coinsReward: 25,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'tech_g6_hydraulics',
      title: 'Hydraulics Hero',
      description: 'Explore hydraulics and pneumatics in real-world applications!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Technology', topicId: 'systems', subtopicId: 'hydraulics_pneumatics',
      engineType: 'adventureJourney', emoji: '🚿', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 120, coinsReward: 24,
      extras: {'stages': 6, 'theme': 'engineering_lab'},
    ),

    // SOCIAL SCIENCES — Grade 6 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g6_world',
      title: 'World Geography',
      description: 'Chart all continents and oceans on this global adventure!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'continents_oceans',
      engineType: 'explorerMap', emoji: '🌐', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 120, coinsReward: 24, isFeatured: true,
      extras: {'mapScale': 'world', 'pinCount': 14, 'mapRegion': 'world'},
    ),
    GameCatalogEntry(
      id: 'ssc_g6_slave_trade',
      title: 'Transatlantic History',
      description: 'Explore the transatlantic slave trade and its global impact!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'slave_trade',
      engineType: 'explorerMap', emoji: '⛵', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 130, coinsReward: 26,
      extras: {'mapScale': 'world', 'pinCount': 10},
    ),
    GameCatalogEntry(
      id: 'ssc_g6_sa_economy',
      title: 'Economic Explorer',
      description: 'Explore economic activities and industries across South Africa!',
      grade: 'grade6', grades: ['grade6'],
      subject: 'Social Sciences', topicId: 'economics', subtopicId: 'economic_activities',
      engineType: 'explorerMap', emoji: '🏭', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 115, coinsReward: 23,
      extras: {'mapScale': 'country', 'pinCount': 9},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // SENIOR PHASE — GRADE 7
    // ═══════════════════════════════════════════════════════════════════════════

    // MATHEMATICS ─────────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'math_g7_algebra',
      title: 'Algebra Arena',
      description: 'Solve simple equations and pull the rope to victory!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'algebra', subtopicId: 'simple_equations',
      engineType: 'tugOfWar', emoji: '📐', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),
    GameCatalogEntry(
      id: 'math_g7_exponents',
      title: 'Exponent Explosion',
      description: 'Master powers and exponents in this explosive challenge!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'numbers', subtopicId: 'exponents',
      engineType: 'tugOfWar', emoji: '💥', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'multiplierMin': 2, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'math_g7_geometry',
      title: 'Geometry Galaxy',
      description: 'Classify triangles, quadrilaterals and their properties!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'geometry', subtopicId: 'triangles_quads',
      engineType: 'adventureJourney', emoji: '🔺', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 7, 'theme': 'geometry_world'},
    ),
    GameCatalogEntry(
      id: 'math_g7_functions',
      title: 'Function Factory',
      description: 'Explore input-output machines and build function tables!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'functions', subtopicId: 'function_tables',
      engineType: 'sequenceBuilder', emoji: '⚙️', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'math_g7_graphs',
      title: 'Graph Guardian',
      description: 'Draw and interpret graphs including scatter plots and histograms!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'data', subtopicId: 'advanced_graphs',
      engineType: 'adventureJourney', emoji: '📈', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 7, 'theme': 'data_lab'},
    ),
    GameCatalogEntry(
      id: 'math_g7_probability',
      title: 'Probability Pro',
      description: 'Master theoretical and experimental probability!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'data', subtopicId: 'probability',
      engineType: 'adventureJourney', emoji: '🎲', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 6, 'theme': 'probability_lab'},
    ),
    GameCatalogEntry(
      id: 'math_g7_integers',
      title: 'Integer Infinity',
      description: 'Add, subtract, multiply and divide integers like a pro!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Mathematics', topicId: 'integers', subtopicId: 'integer_operations',
      engineType: 'tugOfWar', emoji: '⚡', color: Color(0xFFFF6B35),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    // ENGLISH FAL — Grade 7 ───────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'eng_g7_essay',
      title: 'Essay Express',
      description: 'Race to build perfect essay structure and master formal language!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'writing', subtopicId: 'essay_structure',
      engineType: 'runnerCollector', emoji: '✍️', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'speed': 2.2, 'collectMode': 'essayElements'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_grammar',
      title: 'Grammar Gladiator',
      description: 'Master subject-verb agreement, tenses and complex sentences!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'grammar', subtopicId: 'complex_grammar',
      engineType: 'runnerCollector', emoji: '⚔️', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'speed': 2.0, 'collectMode': 'partsOfSpeech'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_poetry',
      title: 'Poetry Power',
      description: 'Analyse poems, identify devices and master literary terms!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'literature', subtopicId: 'poetry_analysis',
      engineType: 'adventureJourney', emoji: '🎭', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 7, 'theme': 'theatre'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_narrative',
      title: 'Narrative Navigator',
      description: 'Build engaging narratives using story structure and literary devices!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'writing', subtopicId: 'narrative_writing',
      engineType: 'sequenceBuilder', emoji: '📖', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'eng_g7_dialogue',
      title: 'Dialogue Dash',
      description: 'Master direct and indirect speech, and formal vs informal language!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'language', subtopicId: 'speech_and_register',
      engineType: 'runnerCollector', emoji: '💬', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'speed': 2.0, 'collectMode': 'words'},
    ),

    // NATURAL SCIENCES — Grade 7 ──────────────────────────────────────────────
    GameCatalogEntry(
      id: 'sci_g7_chemistry',
      title: 'Chemical Lab',
      description: 'Enter the lab and master elements, compounds and mixtures!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'chemistry', subtopicId: 'elements_compounds',
      engineType: 'adventureJourney', emoji: '⚗️', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'stages': 8, 'theme': 'laboratory'},
    ),
    GameCatalogEntry(
      id: 'sci_g7_periodic_table',
      title: 'Periodic Table Quest',
      description: 'Explore the elements of the periodic table in this chemical adventure!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'chemistry', subtopicId: 'periodic_table',
      engineType: 'explorerMap', emoji: '⚛️', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'mapScale': 'table', 'pinCount': 18},
    ),
    GameCatalogEntry(
      id: 'sci_g7_electricity',
      title: 'Electricity Empire',
      description: 'Master circuits, current, voltage and resistance!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'electricity', subtopicId: 'circuits',
      engineType: 'sequenceBuilder', emoji: '💡', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 7},
    ),
    GameCatalogEntry(
      id: 'sci_g7_ecology',
      title: 'Ecology Explorer',
      description: 'Understand ecosystems, biosphere layers and biodiversity!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'ecology', subtopicId: 'biosphere',
      engineType: 'adventureJourney', emoji: '🌿', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 7, 'theme': 'ecosystem'},
    ),
    GameCatalogEntry(
      id: 'sci_g7_solar_system',
      title: 'Solar System Secrets',
      description: 'Explore the sun-earth-moon relationship and seasons!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'earth_science', subtopicId: 'solar_system',
      engineType: 'explorerMap', emoji: '🌙', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'mapScale': 'solar', 'pinCount': 9},
    ),
    GameCatalogEntry(
      id: 'sci_g7_microorganisms',
      title: 'Micro World',
      description: 'Explore the world of micro-organisms and how they affect us!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'biology', subtopicId: 'microorganisms',
      engineType: 'adventureJourney', emoji: '🦠', color: Color(0xFF00BFA5),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 6, 'theme': 'laboratory'},
    ),

    // TECHNOLOGY — Grade 7 ────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'tech_g7_design',
      title: 'Design & Make',
      description: 'Follow the IDMEC design process from brief to prototype in this epic journey!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'design', subtopicId: 'design_process',
      engineType: 'sequenceBuilder', emoji: '🔧', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'tech_g7_structures',
      title: 'Structural Engineer',
      description: 'Design and test structures — cranes, bridges and towers!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'structures', subtopicId: 'advanced_structures',
      engineType: 'adventureJourney', emoji: '🏗️', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6, 'theme': 'construction'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_mechanisms',
      title: 'Mechanisms Mission',
      description: 'Master levers, gears, pulleys and linkages in real applications!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'mechanisms', subtopicId: 'advanced_mechanisms',
      engineType: 'sequenceBuilder', emoji: '⚙️', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'tech_g7_electronics',
      title: 'Electronics Lab',
      description: 'Explore electromagnetic induction and electric circuits!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electronics', subtopicId: 'electromagnets',
      engineType: 'adventureJourney', emoji: '🔌', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6, 'theme': 'electronics_lab'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_graphical',
      title: 'Graphical Communicator',
      description: 'Master 2D drawings, orthographic projections and design sketches!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'graphical_communication', subtopicId: '2d_drawings',
      engineType: 'adventureJourney', emoji: '📏', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 6, 'theme': 'design_studio'},
    ),

    // SOCIAL SCIENCES — Grade 7 ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ssc_g7_heritage',
      title: 'History & Heritage',
      description: 'Explore the journey of apartheid, democracy and Nelson Mandela!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'apartheid_democracy',
      engineType: 'explorerMap', emoji: '✊', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'mapScale': 'country', 'pinCount': 12, 'mapRegion': 'south_africa'},
    ),
    GameCatalogEntry(
      id: 'ssc_g7_mali',
      title: 'Mali & Timbuktu',
      description: 'Journey through the great Mali Empire and discover Timbuktu!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'mali_timbuktu',
      engineType: 'explorerMap', emoji: '🏜️', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'mapScale': 'continent', 'pinCount': 8},
    ),
    GameCatalogEntry(
      id: 'ssc_g7_map_skills',
      title: 'Map Master',
      description: 'Use advanced map skills — scale, coordinates and GIS concepts!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'advanced_map_skills',
      engineType: 'explorerMap', emoji: '🧭', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'mapScale': 'world', 'pinCount': 12},
    ),
    GameCatalogEntry(
      id: 'ssc_g7_disasters',
      title: 'Disaster Response',
      description: 'Learn about natural disasters and how communities respond!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'natural_disasters',
      engineType: 'adventureJourney', emoji: '🌊', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 7, 'theme': 'disaster_response'},
    ),
    GameCatalogEntry(
      id: 'ssc_g7_colonisation',
      title: 'Colonial History',
      description: 'Explore the colonisation of the Cape and its lasting impact!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'colonisation',
      engineType: 'explorerMap', emoji: '⛵', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'mapScale': 'country', 'pinCount': 10},
    ),
    GameCatalogEntry(
      id: 'ssc_g7_conservation',
      title: 'Conservation Mission',
      description: 'Protect natural resources and promote environmental sustainability!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'conservation',
      engineType: 'explorerMap', emoji: '🌱', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'mapScale': 'country', 'pinCount': 9},
    ),

    // EMS — Grade 7 ───────────────────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ems_g7_budget',
      title: 'Budget Boss',
      description: 'Create personal budgets and make smart money decisions!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'financial_literacy', subtopicId: 'budgeting',
      engineType: 'adventureJourney', emoji: '💰', color: Color(0xFF009688),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isFeatured: true,
      extras: {'stages': 6, 'theme': 'bank'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_entrepreneur',
      title: 'Entrepreneur Empire',
      description: 'Start your business empire and learn the basics of entrepreneurship!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'business', subtopicId: 'entrepreneurship',
      engineType: 'adventureJourney', emoji: '🏬', color: Color(0xFF009688),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 7, 'theme': 'business_world'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_economy',
      title: 'Economy Explorer',
      description: 'Understand supply and demand, needs and wants in the economy!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'economics', subtopicId: 'supply_demand',
      engineType: 'tugOfWar', emoji: '📊', color: Color(0xFF009688),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'multiplierMin': 2, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'ems_g7_accounting',
      title: 'Accounting Academy',
      description: 'Learn financial records, income statements and balance sheets!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'accounting', subtopicId: 'financial_records',
      engineType: 'sequenceBuilder', emoji: '📒', color: Color(0xFF009688),
      difficulty: 'hard', xpReward: 145, coinsReward: 29,
      extras: {'stages': 6},
    ),
    GameCatalogEntry(
      id: 'ems_g7_inequality',
      title: 'Inequality Insight',
      description: 'Explore poverty, inequality and how communities can thrive!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'economics', subtopicId: 'poverty_inequality',
      engineType: 'explorerMap', emoji: '⚖️', color: Color(0xFF009688),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'mapScale': 'country', 'pinCount': 9},
    ),

    // LIFE SKILLS — Cross-Grade ───────────────────────────────────────────────
    GameCatalogEntry(
      id: 'ls_g4_5_6_health',
      title: 'Health & Wellness Hero',
      description: 'Master health, nutrition and personal well-being decisions!',
      grade: 'grade4', grades: ['grade4', 'grade5', 'grade6'],
      subject: 'Life Skills', topicId: 'health', subtopicId: 'healthy_choices',
      engineType: 'adventureJourney', emoji: '💪', color: Color(0xFFFF9800),
      difficulty: 'medium', xpReward: 90, coinsReward: 18,
      extras: {'stages': 5, 'theme': 'health_clinic'},
    ),
    GameCatalogEntry(
      id: 'ls_g7_life_decisions',
      title: 'Life Choices Champion',
      description: 'Navigate real-life decisions around health, relationships and future goals!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Life Skills', topicId: 'personal_development', subtopicId: 'life_choices',
      engineType: 'adventureJourney', emoji: '🎯', color: Color(0xFFFF9800),
      difficulty: 'hard', xpReward: 140, coinsReward: 28,
      extras: {'stages': 6, 'theme': 'life_journey'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — CIRCUIT BUILDER (Technology: Electric Circuits)
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'tech_g7_circuit_series_1',
      title: 'Series Circuit Starter',
      description: 'Build a basic series circuit with one battery and one bulb!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'series_circuits',
      engineType: 'circuitBuilder', emoji: '⚡', color: Color(0xFF7C4DFF),
      difficulty: 'easy', xpReward: 80, coinsReward: 16, isNew: true, isFeatured: true,
      extras: {'questionCount': 5, 'difficulty': 'easy'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_switches',
      title: 'Switch Masters',
      description: 'Control circuits using switches — open and close the path of current!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'switches',
      engineType: 'circuitBuilder', emoji: '🔘', color: Color(0xFF7C4DFF),
      difficulty: 'easy', xpReward: 80, coinsReward: 16, isNew: true,
      extras: {'questionCount': 5, 'difficulty': 'easy'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_components',
      title: 'Component Challenge',
      description: 'Identify batteries, bulbs, resistors and switches in circuit diagrams!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'components',
      engineType: 'circuitBuilder', emoji: '🔋', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'questionCount': 7, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_parallel',
      title: 'Parallel Circuit Pro',
      description: 'Master parallel circuits where current splits into multiple paths!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'parallel_circuits',
      engineType: 'circuitBuilder', emoji: '⚡', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'questionCount': 7, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_resistors',
      title: 'Resistor Ranger',
      description: 'Use resistors to control current and protect components in circuits!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'resistors',
      engineType: 'circuitBuilder', emoji: '⬛', color: Color(0xFF7C4DFF),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'questionCount': 6, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_buzzers',
      title: 'Buzzer Builder',
      description: 'Wire circuits with buzzers and learn about transducers!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'transducers',
      engineType: 'circuitBuilder', emoji: '🔔', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 130, coinsReward: 26, isNew: true,
      extras: {'questionCount': 8, 'difficulty': 'hard'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_measuring',
      title: 'Measurement Masters',
      description: 'Place ammeters and voltmeters correctly in series and parallel!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'measuring',
      engineType: 'circuitBuilder', emoji: '🅰️', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 140, coinsReward: 28, isNew: true,
      extras: {'questionCount': 8, 'difficulty': 'hard'},
    ),
    GameCatalogEntry(
      id: 'tech_g7_circuit_design',
      title: 'Circuit Design Grand Prix',
      description: 'Complete advanced circuit challenges — the ultimate Grade 7 circuit test!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Technology', topicId: 'electric_circuits', subtopicId: 'circuit_design',
      engineType: 'circuitBuilder', emoji: '🏆', color: Color(0xFF7C4DFF),
      difficulty: 'hard', xpReward: 160, coinsReward: 32, isNew: true, isFeatured: true,
      extras: {'questionCount': 10, 'difficulty': 'hard'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — BUDGET BUILDER (EMS: Personal Finance & Budgeting)
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'ems_g7_budget_needs_wants',
      title: 'Needs vs Wants',
      description: 'Sort items into Needs, Wants and Skip to build smart spending habits!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'needs_wants',
      engineType: 'budgetBuilder', emoji: '💰', color: Color(0xFF00897B),
      difficulty: 'easy', xpReward: 80, coinsReward: 16, isNew: true, isFeatured: true,
      extras: {'questionCount': 4, 'difficulty': 'easy'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_pocket_money',
      title: 'Pocket Money Planner',
      description: 'Manage R300 pocket money wisely across school supplies and fun!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'budgeting',
      engineType: 'budgetBuilder', emoji: '💵', color: Color(0xFF00897B),
      difficulty: 'easy', xpReward: 80, coinsReward: 16, isNew: true,
      extras: {'questionCount': 4, 'difficulty': 'easy'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_family',
      title: 'Family Budget Boss',
      description: 'Help manage the monthly family budget of R800 — essential needs first!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'household_budget',
      engineType: 'budgetBuilder', emoji: '🏠', color: Color(0xFF00897B),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'questionCount': 5, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_school_trip',
      title: 'School Trip Planner',
      description: 'Plan the class trip budget — transport, entry fees and lunches!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'event_budgeting',
      engineType: 'budgetBuilder', emoji: '🚌', color: Color(0xFF00897B),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'questionCount': 5, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_savings',
      title: 'Savings Superstar',
      description: 'Learn to save 10% before spending — build your emergency fund habit!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'savings',
      engineType: 'budgetBuilder', emoji: '🏦', color: Color(0xFF00897B),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'questionCount': 5, 'difficulty': 'medium'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_business',
      title: 'Young Entrepreneur',
      description: 'Manage income from your small business — stock, savings and spending!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'entrepreneurship', subtopicId: 'business_budget',
      engineType: 'budgetBuilder', emoji: '📦', color: Color(0xFF00897B),
      difficulty: 'hard', xpReward: 140, coinsReward: 28, isNew: true, isFeatured: true,
      extras: {'questionCount': 6, 'difficulty': 'hard'},
    ),
    GameCatalogEntry(
      id: 'ems_g7_budget_household_crisis',
      title: 'Budget Crisis Manager',
      description: 'Tough month ahead — prioritise wisely when money is tight!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'EMS', topicId: 'personal_finance', subtopicId: 'crisis_budgeting',
      engineType: 'budgetBuilder', emoji: '⚠️', color: Color(0xFF00897B),
      difficulty: 'hard', xpReward: 150, coinsReward: 30, isNew: true,
      extras: {'questionCount': 7, 'difficulty': 'hard'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — NATURAL SCIENCES (Existing engines — expanded content)
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'ns_g7_atoms_elements',
      title: 'Atom Academy',
      description: 'Discover atoms, elements and the periodic table — the building blocks!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'matter_materials', subtopicId: 'atoms',
      engineType: 'tugOfWar', emoji: '⚛️', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'ns_g7_energy_forms',
      title: 'Energy Transformer',
      description: 'Match energy forms: kinetic, potential, chemical, electrical and more!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'energy_change', subtopicId: 'energy_forms',
      engineType: 'tugOfWar', emoji: '💥', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'ns_g7_cells_organisms',
      title: 'Cell Explorer',
      description: 'Navigate the microscopic world of cells — plant vs animal cell quiz!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'life_living', subtopicId: 'cells',
      engineType: 'explorerMap', emoji: '🔬', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'mapType': 'cell_map'},
    ),
    GameCatalogEntry(
      id: 'ns_g7_ecosystems',
      title: 'Ecosystem Explorer',
      description: 'Explore South African biomes — grasslands, forests and deserts!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'life_living', subtopicId: 'ecosystems',
      engineType: 'explorerMap', emoji: '🌿', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'mapType': 'sa_biomes'},
    ),
    GameCatalogEntry(
      id: 'ns_g7_physical_changes',
      title: 'State Change Challenge',
      description: 'Race through melting, evaporation and condensation science questions!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'matter_materials', subtopicId: 'physical_changes',
      engineType: 'runnerCollector', emoji: '🧊', color: Color(0xFF00BFA5),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'speed': 'medium', 'theme': 'lab'},
    ),
    GameCatalogEntry(
      id: 'ns_g7_food_chains',
      title: 'Food Chain Runner',
      description: 'Collect producers, consumers and decomposers in the right order!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Natural Sciences', topicId: 'life_living', subtopicId: 'food_chains',
      engineType: 'runnerCollector', emoji: '🦁', color: Color(0xFF00BFA5),
      difficulty: 'easy', xpReward: 90, coinsReward: 18, isNew: true,
      extras: {'speed': 'slow', 'theme': 'savanna'},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — SOCIAL SCIENCES: GEOGRAPHY
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'ss_g7_geo_climate',
      title: 'Climate Zone Champion',
      description: 'Match climate zones on the world map — tropical, arid, temperate and more!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'climate_zones',
      engineType: 'explorerMap', emoji: '🌍', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'mapType': 'world_climate'},
    ),
    GameCatalogEntry(
      id: 'ss_g7_geo_rivers',
      title: 'River Explorer',
      description: 'Locate Africa\'s major rivers: the Nile, Congo, Zambezi and Orange!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'rivers',
      engineType: 'explorerMap', emoji: '🏞️', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 90, coinsReward: 18, isNew: true,
      extras: {'mapType': 'africa_rivers'},
    ),
    GameCatalogEntry(
      id: 'ss_g7_geo_settlement',
      title: 'Settlement Sequence',
      description: 'Arrange settlement types from rural to urban — hamlet to megacity!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'settlements',
      engineType: 'sequenceBuilder', emoji: '🏙️', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'sequenceType': 'settlements'},
    ),
    GameCatalogEntry(
      id: 'ss_g7_geo_population',
      title: 'Population Patterns',
      description: 'Understand push and pull factors of migration in South Africa!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'geography', subtopicId: 'population',
      engineType: 'tugOfWar', emoji: '👥', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — SOCIAL SCIENCES: HISTORY
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'ss_g7_hist_apartheid',
      title: 'Apartheid Journey',
      description: 'Trace the key events of apartheid from 1948 to the first democratic election!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'apartheid',
      engineType: 'adventureJourney', emoji: '🕊️', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 120, coinsReward: 24, isNew: true, isFeatured: true,
      extras: {'stages': 5, 'theme': 'south_africa_history'},
    ),
    GameCatalogEntry(
      id: 'ss_g7_hist_timeline',
      title: 'History Timeline Builder',
      description: 'Sequence key South African historical events in the correct order!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'timeline',
      engineType: 'sequenceBuilder', emoji: '📅', color: Color(0xFF43A047),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'sequenceType': 'sa_history'},
    ),
    GameCatalogEntry(
      id: 'ss_g7_hist_leaders',
      title: 'Leaders of Change',
      description: 'Match South African freedom fighters to their contributions and role!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'leaders',
      engineType: 'tugOfWar', emoji: '✊', color: Color(0xFF43A047),
      difficulty: 'easy', xpReward: 90, coinsReward: 18, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'ss_g7_hist_democracy',
      title: 'Democracy Champion',
      description: 'Test your knowledge of South Africa\'s constitution and democratic rights!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'Social Sciences', topicId: 'history', subtopicId: 'democracy',
      engineType: 'tugOfWar', emoji: '🗳️', color: Color(0xFF43A047),
      difficulty: 'hard', xpReward: 140, coinsReward: 28, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // GRADE 7 — ENGLISH FAL (First Additional Language)
    // ═══════════════════════════════════════════════════════════════════════════

    GameCatalogEntry(
      id: 'eng_g7_comprehension',
      title: 'Reading Comprehension Race',
      description: 'Read passages and answer questions about tone, meaning and inference!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'reading', subtopicId: 'comprehension',
      engineType: 'tugOfWar', emoji: '📖', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 110, coinsReward: 22, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'eng_g7_grammar_advanced',
      title: 'Grammar Grand Prix',
      description: 'Master clauses, tenses, voice and punctuation in this grammar race!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'language_structures', subtopicId: 'grammar',
      engineType: 'runnerCollector', emoji: '📝', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 130, coinsReward: 26, isNew: true,
      extras: {'speed': 'fast', 'theme': 'library'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_figurative_language',
      title: 'Figurative Language Fighter',
      description: 'Identify similes, metaphors, personification and hyperbole in texts!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'language_structures', subtopicId: 'figurative_language',
      engineType: 'tugOfWar', emoji: '🎭', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 140, coinsReward: 28, isNew: true,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),
    GameCatalogEntry(
      id: 'eng_g7_vocabulary',
      title: 'Word Power Challenge',
      description: 'Build your Grade 7 vocabulary — synonyms, antonyms and context clues!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'vocabulary', subtopicId: 'word_meanings',
      engineType: 'multiplesMerge', emoji: '💬', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'wordFamily': 'grade7_vocab'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_writing_sequence',
      title: 'Essay Structure Builder',
      description: 'Arrange introduction, body paragraphs and conclusion in the right order!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'writing', subtopicId: 'essay_structure',
      engineType: 'sequenceBuilder', emoji: '✍️', color: Color(0xFFE91E63),
      difficulty: 'medium', xpReward: 100, coinsReward: 20, isNew: true,
      extras: {'sequenceType': 'essay'},
    ),
    GameCatalogEntry(
      id: 'eng_g7_poetry',
      title: 'Poetry Pathfinder',
      description: 'Explore rhyme schemes, rhythm and poetic devices in SA poetry!',
      grade: 'grade7', grades: ['grade7'],
      subject: 'English', topicId: 'literature', subtopicId: 'poetry',
      engineType: 'adventureJourney', emoji: '🌹', color: Color(0xFFE91E63),
      difficulty: 'hard', xpReward: 140, coinsReward: 28, isNew: true, isFeatured: true,
      extras: {'stages': 4, 'theme': 'poetry_garden'},
    ),
  ];

  static List<GameCatalogEntry> forGrade(String grade) =>
      all.where((e) => e.grades.contains(grade) || e.grades.contains('all')).toList();

  static List<GameCatalogEntry> forSubject(String subject, String grade) =>
      forGrade(grade).where((e) => e.subject == subject).toList();

  static List<GameCatalogEntry> featured(String grade) =>
      forGrade(grade).where((e) => e.isFeatured).toList();
}
