import 'package:flutter/material.dart';

class GameCatalogEntry {
  final String id;
  final String title;
  final String description;
  final String grade;
  final List<String> grades;
  final String subject;
  final String topicId;
  final String subtopicId;
  final String engineType;
  final String emoji;
  final Color color;
  final String difficulty;
  final int xpReward;
  final int coinsReward;
  final bool isNew;
  final bool isFeatured;
  final Map<String, dynamic> extras;

  const GameCatalogEntry({
    required this.id,
    required this.title,
    required this.description,
    required this.grade,
    required this.grades,
    required this.subject,
    required this.topicId,
    required this.subtopicId,
    required this.engineType,
    required this.emoji,
    required this.color,
    required this.difficulty,
    required this.xpReward,
    required this.coinsReward,
    this.isNew = false,
    this.isFeatured = false,
    this.extras = const {},
  });
}

class GameCatalog {
  static const List<GameCatalogEntry> all = [
    // ─── MATHEMATICS — tugOfWar engine ───────────────────────────────────────

    GameCatalogEntry(
      id: 'math_g1_counting',
      title: 'Number Counting Duel',
      description: 'Count and compare numbers 1–20 in a battle against the AI!',
      grade: 'grade1',
      grades: ['grade1'],
      subject: 'Mathematics',
      topicId: 'numbers',
      subtopicId: 'counting',
      engineType: 'tugOfWar',
      emoji: '🔢',
      color: Color(0xFFFF6B35),
      difficulty: 'easy',
      xpReward: 50,
      coinsReward: 10,
      extras: {'multiplierMin': 1, 'multiplierMax': 5},
    ),

    GameCatalogEntry(
      id: 'math_g2_addition',
      title: 'Addition Adventure',
      description: 'Add numbers up to 50 and outpull your rival!',
      grade: 'grade2',
      grades: ['grade2'],
      subject: 'Mathematics',
      topicId: 'operations',
      subtopicId: 'addition',
      engineType: 'tugOfWar',
      emoji: '➕',
      color: Color(0xFFFF6B35),
      difficulty: 'easy',
      xpReward: 60,
      coinsReward: 12,
      extras: {'multiplierMin': 1, 'multiplierMax': 10},
    ),

    GameCatalogEntry(
      id: 'math_g3_tables',
      title: 'Times Tables Rookie',
      description: 'Master multiplication tables 2×, 3×, 4× and 5×!',
      grade: 'grade3',
      grades: ['grade3'],
      subject: 'Mathematics',
      topicId: 'multiplication',
      subtopicId: 'tables_2_5',
      engineType: 'tugOfWar',
      emoji: '✖️',
      color: Color(0xFFFF6B35),
      difficulty: 'medium',
      xpReward: 80,
      coinsReward: 15,
      isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 5},
    ),

    GameCatalogEntry(
      id: 'math_g4_multiplication',
      title: 'Multiplication Master',
      description: 'Conquer times tables 2–12 and defeat the AI champion!',
      grade: 'grade4',
      grades: ['grade4'],
      subject: 'Mathematics',
      topicId: 'multiplication',
      subtopicId: 'tables_2_12',
      engineType: 'tugOfWar',
      emoji: '🧮',
      color: Color(0xFFFF6B35),
      difficulty: 'medium',
      xpReward: 100,
      coinsReward: 20,
      isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    GameCatalogEntry(
      id: 'math_g5_fractions',
      title: 'Fraction Faceoff',
      description: 'Compare fractions and prove who truly knows their halves!',
      grade: 'grade5',
      grades: ['grade5'],
      subject: 'Mathematics',
      topicId: 'fractions',
      subtopicId: 'compare_fractions',
      engineType: 'tugOfWar',
      emoji: '½',
      color: Color(0xFFFF6B35),
      difficulty: 'medium',
      xpReward: 110,
      coinsReward: 22,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    GameCatalogEntry(
      id: 'math_g6_percentages',
      title: 'Percentage Clash',
      description: 'Tackle percentages and ratios in this intense tug of war!',
      grade: 'grade6',
      grades: ['grade6'],
      subject: 'Mathematics',
      topicId: 'percentages',
      subtopicId: 'ratios_and_percent',
      engineType: 'tugOfWar',
      emoji: '%',
      color: Color(0xFFFF6B35),
      difficulty: 'hard',
      xpReward: 130,
      coinsReward: 25,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    GameCatalogEntry(
      id: 'math_g7_algebra',
      title: 'Algebra Arena',
      description: 'Solve simple equations and pull the rope to victory!',
      grade: 'grade7',
      grades: ['grade7'],
      subject: 'Mathematics',
      topicId: 'algebra',
      subtopicId: 'simple_equations',
      engineType: 'tugOfWar',
      emoji: '📐',
      color: Color(0xFFFF6B35),
      difficulty: 'hard',
      xpReward: 150,
      coinsReward: 30,
      isNew: true,
      isFeatured: true,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    // ─── NATURAL SCIENCES — adventureJourney engine ───────────────────────────

    GameCatalogEntry(
      id: 'sci_g1_animals',
      title: 'Animal Safari',
      description: 'Journey through the wild and classify mammals, birds and reptiles!',
      grade: 'grade1',
      grades: ['grade1'],
      subject: 'Natural Sciences',
      topicId: 'animals',
      subtopicId: 'animal_classification',
      engineType: 'adventureJourney',
      emoji: '🦁',
      color: Color(0xFF00BFA5),
      difficulty: 'easy',
      xpReward: 50,
      coinsReward: 10,
      extras: {'stages': 4, 'theme': 'safari'},
    ),

    GameCatalogEntry(
      id: 'sci_g2_plants',
      title: 'Plant Life Journey',
      description: 'Follow a seed through its incredible plant growth stages!',
      grade: 'grade2',
      grades: ['grade2'],
      subject: 'Natural Sciences',
      topicId: 'plants',
      subtopicId: 'growth_stages',
      engineType: 'adventureJourney',
      emoji: '🌱',
      color: Color(0xFF00BFA5),
      difficulty: 'easy',
      xpReward: 60,
      coinsReward: 12,
      extras: {'stages': 5, 'theme': 'garden'},
    ),

    GameCatalogEntry(
      id: 'sci_g3_nutrition',
      title: 'Food & Nutrition Quest',
      description: 'Explore healthy and unhealthy foods on an epic quest!',
      grade: 'grade3',
      grades: ['grade3'],
      subject: 'Natural Sciences',
      topicId: 'nutrition',
      subtopicId: 'healthy_foods',
      engineType: 'adventureJourney',
      emoji: '🥦',
      color: Color(0xFF00BFA5),
      difficulty: 'easy',
      xpReward: 70,
      coinsReward: 14,
      extras: {'stages': 4, 'theme': 'kitchen'},
    ),

    GameCatalogEntry(
      id: 'sci_g4_water',
      title: 'Water Cycle Adventure',
      description: 'Travel through evaporation, condensation and precipitation!',
      grade: 'grade4',
      grades: ['grade4'],
      subject: 'Natural Sciences',
      topicId: 'water',
      subtopicId: 'water_cycle',
      engineType: 'adventureJourney',
      emoji: '💧',
      color: Color(0xFF00BFA5),
      difficulty: 'medium',
      xpReward: 90,
      coinsReward: 18,
      isFeatured: true,
      extras: {'stages': 6, 'theme': 'weather'},
    ),

    GameCatalogEntry(
      id: 'sci_g5_body',
      title: 'Human Body Explorer',
      description: 'Navigate the human body and discover its amazing systems and organs!',
      grade: 'grade5',
      grades: ['grade5'],
      subject: 'Natural Sciences',
      topicId: 'human_body',
      subtopicId: 'body_systems',
      engineType: 'adventureJourney',
      emoji: '🫀',
      color: Color(0xFF00BFA5),
      difficulty: 'medium',
      xpReward: 110,
      coinsReward: 22,
      extras: {'stages': 7, 'theme': 'anatomy'},
    ),

    GameCatalogEntry(
      id: 'sci_g6_ecosystem',
      title: 'Ecosystem Explorer',
      description: 'Discover biomes and food chains across Earth\'s ecosystems!',
      grade: 'grade6',
      grades: ['grade6'],
      subject: 'Natural Sciences',
      topicId: 'ecosystems',
      subtopicId: 'biomes_food_chains',
      engineType: 'adventureJourney',
      emoji: '🌿',
      color: Color(0xFF00BFA5),
      difficulty: 'medium',
      xpReward: 120,
      coinsReward: 24,
      extras: {'stages': 6, 'theme': 'wilderness'},
    ),

    GameCatalogEntry(
      id: 'sci_g7_chemistry',
      title: 'Chemical Lab',
      description: 'Enter the lab and master elements, compounds and mixtures!',
      grade: 'grade7',
      grades: ['grade7'],
      subject: 'Natural Sciences',
      topicId: 'chemistry',
      subtopicId: 'elements_compounds',
      engineType: 'adventureJourney',
      emoji: '⚗️',
      color: Color(0xFF00BFA5),
      difficulty: 'hard',
      xpReward: 150,
      coinsReward: 30,
      isNew: true,
      extras: {'stages': 8, 'theme': 'laboratory'},
    ),

    // ─── ENGLISH HOME LANGUAGE — runnerCollector engine ───────────────────────

    GameCatalogEntry(
      id: 'eng_g1_letters',
      title: 'Letter Land',
      description: 'Run through Letter Land collecting alphabet letters and phonics!',
      grade: 'grade1',
      grades: ['grade1'],
      subject: 'English',
      topicId: 'phonics',
      subtopicId: 'alphabet_phonics',
      engineType: 'runnerCollector',
      emoji: '🔤',
      color: Color(0xFFE91E63),
      difficulty: 'easy',
      xpReward: 50,
      coinsReward: 10,
      extras: {'speed': 1.0, 'collectMode': 'letters'},
    ),

    GameCatalogEntry(
      id: 'eng_g2_words',
      title: 'Word Wizard',
      description: 'Sprint and collect simple words to build amazing sentences!',
      grade: 'grade2',
      grades: ['grade2'],
      subject: 'English',
      topicId: 'vocabulary',
      subtopicId: 'simple_words',
      engineType: 'runnerCollector',
      emoji: '✨',
      color: Color(0xFFE91E63),
      difficulty: 'easy',
      xpReward: 60,
      coinsReward: 12,
      extras: {'speed': 1.2, 'collectMode': 'words'},
    ),

    GameCatalogEntry(
      id: 'eng_g3_story',
      title: 'Story Builder',
      description: 'Dash through stories collecting vocabulary and reading gems!',
      grade: 'grade3',
      grades: ['grade3'],
      subject: 'English',
      topicId: 'reading',
      subtopicId: 'vocabulary_reading',
      engineType: 'runnerCollector',
      emoji: '📚',
      color: Color(0xFFE91E63),
      difficulty: 'medium',
      xpReward: 75,
      coinsReward: 15,
      extras: {'speed': 1.4, 'collectMode': 'words'},
    ),

    GameCatalogEntry(
      id: 'eng_g4_grammar',
      title: 'Grammar Hero Run',
      description: 'Race and collect nouns, verbs and adjectives — become a grammar hero!',
      grade: 'grade4',
      grades: ['grade4'],
      subject: 'English',
      topicId: 'grammar',
      subtopicId: 'parts_of_speech',
      engineType: 'runnerCollector',
      emoji: '🦸',
      color: Color(0xFFE91E63),
      difficulty: 'medium',
      xpReward: 90,
      coinsReward: 18,
      isFeatured: true,
      extras: {'speed': 1.6, 'collectMode': 'partsOfSpeech'},
    ),

    GameCatalogEntry(
      id: 'eng_g5_tense',
      title: 'Tense Racer',
      description: 'Zoom through time collecting past, present and future tense words!',
      grade: 'grade5',
      grades: ['grade5'],
      subject: 'English',
      topicId: 'grammar',
      subtopicId: 'tenses',
      engineType: 'runnerCollector',
      emoji: '⏱️',
      color: Color(0xFFE91E63),
      difficulty: 'medium',
      xpReward: 100,
      coinsReward: 20,
      extras: {'speed': 1.8, 'collectMode': 'tenses'},
    ),

    GameCatalogEntry(
      id: 'eng_g6_punctuation',
      title: 'Punctuation Sprint',
      description: 'Sprint through sentences and master all punctuation rules!',
      grade: 'grade6',
      grades: ['grade6'],
      subject: 'English',
      topicId: 'punctuation',
      subtopicId: 'punctuation_rules',
      engineType: 'runnerCollector',
      emoji: '❗',
      color: Color(0xFFE91E63),
      difficulty: 'hard',
      xpReward: 120,
      coinsReward: 24,
      extras: {'speed': 2.0, 'collectMode': 'punctuation'},
    ),

    GameCatalogEntry(
      id: 'eng_g7_essay',
      title: 'Essay Express',
      description: 'Race to build perfect essay structure and master formal language!',
      grade: 'grade7',
      grades: ['grade7'],
      subject: 'English',
      topicId: 'writing',
      subtopicId: 'essay_structure',
      engineType: 'runnerCollector',
      emoji: '✍️',
      color: Color(0xFFE91E63),
      difficulty: 'hard',
      xpReward: 150,
      coinsReward: 30,
      isNew: true,
      extras: {'speed': 2.2, 'collectMode': 'essayElements'},
    ),

    // ─── SOCIAL SCIENCES — explorerMap engine ────────────────────────────────

    GameCatalogEntry(
      id: 'ssc_g1_community',
      title: 'My Community Map',
      description: 'Explore your local community and pin its amazing features!',
      grade: 'grade1',
      grades: ['grade1'],
      subject: 'Social Sciences',
      topicId: 'community',
      subtopicId: 'local_community',
      engineType: 'explorerMap',
      emoji: '🏘️',
      color: Color(0xFF43A047),
      difficulty: 'easy',
      xpReward: 50,
      coinsReward: 10,
      extras: {'mapScale': 'local', 'pinCount': 6},
    ),

    GameCatalogEntry(
      id: 'ssc_g2_neighbourhood',
      title: 'Neighbourhood Explorer',
      description: 'Map transport routes and find community helpers in your area!',
      grade: 'grade2',
      grades: ['grade2'],
      subject: 'Social Sciences',
      topicId: 'neighbourhood',
      subtopicId: 'transport_helpers',
      engineType: 'explorerMap',
      emoji: '🚌',
      color: Color(0xFF43A047),
      difficulty: 'easy',
      xpReward: 60,
      coinsReward: 12,
      extras: {'mapScale': 'neighbourhood', 'pinCount': 8},
    ),

    GameCatalogEntry(
      id: 'ssc_g3_history',
      title: 'Local History Quest',
      description: 'Journey through South Africa\'s early history on an interactive map!',
      grade: 'grade3',
      grades: ['grade3'],
      subject: 'Social Sciences',
      topicId: 'history',
      subtopicId: 'sa_early_history',
      engineType: 'explorerMap',
      emoji: '🏛️',
      color: Color(0xFF43A047),
      difficulty: 'easy',
      xpReward: 70,
      coinsReward: 14,
      extras: {'mapScale': 'country', 'pinCount': 8},
    ),

    GameCatalogEntry(
      id: 'ssc_g4_provinces',
      title: 'SA Provinces Explorer',
      description: 'Discover all 9 South African provinces, their capitals and cool facts!',
      grade: 'grade4',
      grades: ['grade4'],
      subject: 'Social Sciences',
      topicId: 'geography',
      subtopicId: 'sa_provinces',
      engineType: 'explorerMap',
      emoji: '🗺️',
      color: Color(0xFF43A047),
      difficulty: 'medium',
      xpReward: 100,
      coinsReward: 20,
      isFeatured: true,
      extras: {'mapScale': 'country', 'pinCount': 9, 'mapRegion': 'south_africa'},
    ),

    GameCatalogEntry(
      id: 'ssc_g5_africa',
      title: 'African Countries',
      description: 'Pin and explore major countries across the African continent!',
      grade: 'grade5',
      grades: ['grade5'],
      subject: 'Social Sciences',
      topicId: 'geography',
      subtopicId: 'african_countries',
      engineType: 'explorerMap',
      emoji: '🌍',
      color: Color(0xFF43A047),
      difficulty: 'medium',
      xpReward: 110,
      coinsReward: 22,
      extras: {'mapScale': 'continent', 'pinCount': 15, 'mapRegion': 'africa'},
    ),

    GameCatalogEntry(
      id: 'ssc_g6_world',
      title: 'World Geography',
      description: 'Chart all continents and oceans on this global adventure!',
      grade: 'grade6',
      grades: ['grade6'],
      subject: 'Social Sciences',
      topicId: 'geography',
      subtopicId: 'continents_oceans',
      engineType: 'explorerMap',
      emoji: '🌐',
      color: Color(0xFF43A047),
      difficulty: 'medium',
      xpReward: 120,
      coinsReward: 24,
      extras: {'mapScale': 'world', 'pinCount': 14, 'mapRegion': 'world'},
    ),

    GameCatalogEntry(
      id: 'ssc_g7_heritage',
      title: 'History & Heritage',
      description: 'Explore the journey of apartheid, democracy and Nelson Mandela!',
      grade: 'grade7',
      grades: ['grade7'],
      subject: 'Social Sciences',
      topicId: 'history',
      subtopicId: 'apartheid_democracy',
      engineType: 'explorerMap',
      emoji: '✊',
      color: Color(0xFF43A047),
      difficulty: 'hard',
      xpReward: 150,
      coinsReward: 30,
      isNew: true,
      isFeatured: true,
      extras: {'mapScale': 'country', 'pinCount': 12, 'mapRegion': 'south_africa'},
    ),

    // ─── TECHNOLOGY & LIFE SKILLS — mixed engines ────────────────────────────

    GameCatalogEntry(
      id: 'ls_g1_3_lifeskills',
      title: 'Life Skills Adventure',
      description: 'Journey through daily life skills challenges and grow into your best self!',
      grade: 'grade1',
      grades: ['grade1', 'grade2', 'grade3'],
      subject: 'Life Skills',
      topicId: 'life_skills',
      subtopicId: 'daily_skills',
      engineType: 'adventureJourney',
      emoji: '🌟',
      color: Color(0xFFFF9800),
      difficulty: 'easy',
      xpReward: 60,
      coinsReward: 12,
      extras: {'stages': 5, 'theme': 'everyday_life'},
    ),

    GameCatalogEntry(
      id: 'tech_g4_6_challenge',
      title: 'Technology Challenge',
      description: 'Solve real-world STEM problems in this exciting tug of war!',
      grade: 'grade4',
      grades: ['grade4', 'grade5', 'grade6'],
      subject: 'Technology',
      topicId: 'technology',
      subtopicId: 'stem_problems',
      engineType: 'tugOfWar',
      emoji: '⚙️',
      color: Color(0xFF7C4DFF),
      difficulty: 'medium',
      xpReward: 100,
      coinsReward: 20,
      extras: {'multiplierMin': 2, 'multiplierMax': 12},
    ),

    GameCatalogEntry(
      id: 'tech_g5_7_design',
      title: 'Design & Make',
      description: 'Follow the design process from brief to prototype in this epic journey!',
      grade: 'grade5',
      grades: ['grade5', 'grade6', 'grade7'],
      subject: 'Technology',
      topicId: 'design',
      subtopicId: 'design_process',
      engineType: 'adventureJourney',
      emoji: '🔧',
      color: Color(0xFF7C4DFF),
      difficulty: 'medium',
      xpReward: 120,
      coinsReward: 24,
      isNew: true,
      extras: {'stages': 6, 'theme': 'workshop'},
    ),
  ];

  static List<GameCatalogEntry> forGrade(String grade) =>
      all.where((e) => e.grades.contains(grade) || e.grades.contains('all')).toList();

  static List<GameCatalogEntry> forSubject(String subject, String grade) =>
      forGrade(grade).where((e) => e.subject == subject).toList();

  static List<GameCatalogEntry> featured(String grade) =>
      forGrade(grade).where((e) => e.isFeatured).toList();
}
